### PR TITLE
Added 2024 announcements and new banner

### PR DESCRIPTION
**Pull request by mjh316**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [ x] I have tested my code.
- [ x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ x] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
so it's just 1 banner now?

**Comment by mjh316** [comment]
> so it's just 1 banner now?

Yup, and the announcements section has been moved up on the dashboard

**Comment by danielzsh** [comment]
Are we planning to change the banner color? It looks quite jarring, especially in dark mode 😅 I do like having one banner rather than 3 though!

**Comment by SansPapyrus683** [comment]
image

perhaps limit the # of announcements to just 2 or 4?

**Comment by Evang264** [comment]
Indeed, the colour of the banner in dark mode should be addressed first, due to the colour mis-match

**Review by danielzsh — APPROVED** [review]

**Comment by danielzsh** [comment]
do we potentially want to make the banner size a bit larger? it feels a bit small to me rn, but its really fine either way

**Pull request merged**
