### PR TITLE
feb 21 probs

### PR DESCRIPTION
**Pull request by bqi343**

### CODE REVIEW

**Review by HarryWangATX — APPROVED** [review]

**Comment by jessechoe10** [comment]
Add Year of the Cow Silver to "sorting with greedy" and add Just Green Enough to "more on prefix sums"...

**Review by jessechoe10 — APPROVED** [review]

**Comment by HarryWangATX** [comment]
maybe remove some sorting problems cus some of them are way to ez and add some hard ones in instead

**Comment by bqi343** [comment]
> Add Year of the Cow Silver to "sorting with greedy" and add Just Green Enough to "more on prefix sums"...

As I said previously, prefix sums are a fairly small part of only one of the possible solutions. Also, I think Greedy w/ Sorting has enough problems.

**Comment by bqi343** [comment]
> maybe remove some sorting problems cus some of them are way to ez and add some hard ones in instead

make a separate PR?

**Comment by HarryWangATX** [comment]
> > maybe remove some sorting problems cus some of them are way to ez and add some hard ones in instead
> 
> 
> 
> make a separate PR?

sure will do later

**Pull request merged**
