### PR TITLE
Got rid of unnecessary lines

### PR DESCRIPTION
**Pull request by HarryWangATX**

### CODE REVIEW

**Comment by dolphingarlic** [comment]
Lol nice catch

**Comment by dolphingarlic** [comment]
Oops I didn't read the code carefully - the lines aren't actually unnecessary

**Comment by dolphingarlic** [comment]
Basically, those lines compare the second dimension when the first dimensions are equal (so that the cows are sorted by both dimensions instead of only by the first and then randomly by the second)

**Comment by HarryWangATX** [comment]
@dolphingarlic I submitted my code again and it passed. but idk because i think we only need to care about x or y values

**Comment by HarryWangATX** [comment]
cus idt the second dimensuon matters as it will be checked with the if statements

**Pull request merged**
