### PR TITLE
remove skipped/ignored from active dashboard

### PR DESCRIPTION
**Pull request by aaronthechen**
removes skipped and ignored tags from active modules/problems on the dashboard

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

### CODE REVIEW

**Comment by bqi343** [comment]
why? use "ignored" instead of "skipped" if you don't want a problem to show up on the dashboard

**Comment by SansPapyrus683** [comment]
TIL that the "ignored" option exists
i'm probably not the only one

**Comment by SansPapyrus683** [comment]
i feel like we should make it more explicit as to what marking each problem does...

**Comment by bqi343** [comment]
Can add to “using this guide”

**Pull request closed without merging**
