### PR TITLE
Create USACO feb17-lemonade.mdx

### PR DESCRIPTION
**Pull request by MrinallU**
For USACO silver lemonade line. I also need someone to tell me how to find the problem ID.

### CODE REVIEW

**Comment by xyzyzl** [comment]
Problem ID is the three digit number in the problem URL. For lemonade, this is 835

**Comment by thecodingwizard** [comment]
@MrinallU I updated the file to include the USACO ID, and I also updated the LanguageSection tags.

There's one more thing that you need to do: In the file `content/3_Silver/Greedy.mdx`, you need to go to line 81 and update the empty string to be `usaco-835`. The last argument in the Problem constructor is the solution ID, which should match the ID at the top of the solution file.

```
		new Problem(
			'Silver',
			'Lemonade Line',
			'835',
			'Easy',
			false,
			['Sorting'],
			'usaco-835'
		),
```

Thanks!

**Comment by MrinallU** [comment]
@thecodingwizard I did what you suggested and will do the same with my other PR(s)!

**Comment by thecodingwizard** [comment]
Thanks @MrinallU !

**Pull request merged**
