### PR TITLE
Add to contributors list

### PR DESCRIPTION
**Pull request by ady00**
Added Nikita, Jaiman, and myself to the contributors list. 

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

### CODE REVIEW

**Comment by ady00** [comment]
@maggie-j-liu could you review this? Thanks!

**Comment by Aadit-Ambadkar** [comment]
@maggie-j-liu @SansPapyrus683 @cpinitiative/webmaster

**Comment by SansPapyrus683** [comment]
could you also add faris raza?
apparently he's on https://joincpi.org/
but not on the guide

**Comment by ady00** [comment]
ryan added faris raza afaik

**Comment by SansPapyrus683** [comment]
oh yeah, he's been added
also oof, merge conflicts

**Comment by Aadit-Ambadkar** [comment]
resolved the conflicts

**Review by SansPapyrus683 — APPROVED** [review]

**Pull request merged**
