### PR TITLE
Remove Spoiler Tags from module solutions

### LINKED ISSUE #3696: make module solutions consistent
Currently, some module solutions are in spoiler and some are not. We should **remove all spoilers** from module solutions.

### PR DESCRIPTION
**Pull request by ChuangSheep**
Closes #3696 

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

### CODE REVIEW

**Review by SansPapyrus683 — APPROVED** [review]
too good

**Comment by ChuangSheep** [comment]
Before merge, please do double check if everything looks right - there are too many changes

**Comment by ChuangSheep** [comment]
wdym? didn't I left them in spoilers?

**Comment by SansPapyrus683** [comment]
oops typo lmao

**Comment by SansPapyrus683** [comment]
worst case we make another pr

**Pull request merged**
