### PR TITLE
Update CA list

### PR DESCRIPTION
**Pull request by DenialRiver1434**
I am applying for coding club positions and it will help my application significantly if I am bestowed the honor of having my name listed on the usaco.guide GitHub readme. **I joined the team (you can see this on the discord) last month**, but here are some merged pull requests I've authored for good measure (4 major, 1 minor).
https://github.com/cpinitiative/usaco-guide/pull/3745
https://github.com/cpinitiative/usaco-guide/pull/3750
https://github.com/cpinitiative/usaco-guide/pull/3762
https://github.com/cpinitiative/usaco-guide/pull/3773
https://github.com/cpinitiative/usaco-guide/pull/3806

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

### CODE REVIEW

**Comment by fortnitefan441** [comment]
no haha

**Comment by fortnitefan441** [comment]
daniel edited my message: what i meant to say is that he is lying

**Comment by fortnitefan441** [comment]
dont trust

**Comment by fortnitefan441** [comment]
he is a con artist

**Comment by DenialRiver1434** [comment]
It seems that my friend's younger brother has discovered my github (hence the mass deletion) :/

**Comment by fortnitefan441** [comment]
hey daniel im pissed

**Comment by fortnitefan441** [comment]
wait why did you have to explain that 💀

**Comment by ryanchou-dev** [comment]
>v<

**Pull request merged**
