### PR TITLE
Add Dijkstra vis resource

### PR DESCRIPTION
**Pull request by alexyd88**
added link: https://alexyd88.github.io/Dijkstra-Visualizer/ under O(MlogN) Dijkstra resources

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

### CODE REVIEW

**Review by bqi343 — APPROVED** [review]

**Review by bqi343 — CHANGES_REQUESTED** [review]
Actually, this visualizer doesn't look correct.

Screen Shot 2023-02-18 at 8 32 38 PM

The next edge to be explored should be the one with minimum distance, not the maximum. Also, why aren't the distances sorted in increasing order from top to bottom?

**Comment by alexyd88** [comment]
Wait how did you get that? I quickly tested it just now.
image

**Comment by bqi343** [comment]
I just opened the link again: https://alexyd88.github.io/Dijkstra-Visualizer/ and this is what I got:

Screen Shot 2023-02-18 at 8 37 44 PM

**Comment by alexyd88** [comment]
That's weird, because it works consistently for me. I'll look into it and get back to you.

**Comment by alexyd88** [comment]
Apparently my comparator function works slightly differently in firefox and chrome, but it should be fixed now. Can you try the link again?

**Review by bqi343 — APPROVED** [review]

**Pull request merged**
