### PR TITLE
Added another way of File I/O in Python

### PR DESCRIPTION
**Pull request by rickastley1**
I have added another way, dare I say better, of using file input-output in Python

### CODE REVIEW

**Comment by bqi343** [comment]
Why is this better?

**Comment by rickastley1** [comment]
I just thought that instead of changing sys.stdout/stdin this would be better as it sort of cleans up after you. For the existing example, using a print statement anywhere would output onto the file which is not as optimal for debugging, for example. My method only uses file I/O where it is necessary.

**Comment by rickastley1** [comment]
> Why is reading in all lines at the start better?

It takes in each line and inserts it into a list

**Comment by dongliu0426** [comment]
i think it's easier to do `fin.readline()` every single time a line needs to be read.

**Comment by bqi343** [comment]
> i think it's easier to do `fin.readline()` every single time a line needs to be read.

`input()` is even easier :P

> For the existing example, using a print statement anywhere would output onto the file which is not as optimal for debugging, for example. 

I assume that when you're running the program locally, you'd comment out the lines with `sys.stdin` and `sys.stdout`, so you wouldn't be printing to a file. Also, do you not view your program output + debug output together?

**Comment by rickastley1** [comment]
Hmm... true, I guess at this point, it's just an alternative rather than a strictly speaking "better" option
> I assume that when you're running the program locally, you'd comment out the lines with `sys.stdin` and `sys.stdout`, so you wouldn't be printing to a file. Also, do you not view your program output + debug output together?
Too much effort XD.

**Comment by thecodingwizard** [comment]
I think it's a good alternative but I think it's already somewhat provided here? https://usaco.guide/general/io?lang=py#method-1-1

I'll close this PR for now; feel free to keep discussing though...

**Comment by rickastley1** [comment]
Ok thank you

**Pull request closed without merging**
