### PR TITLE
added solution for usaco 1277

### PR DESCRIPTION
**Pull request by chuminjae**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [ ✓] I have tested my code.
- [ ✓] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ✓] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ✓] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
do you want me to just directly make the changes for you

**Comment by chuminjae** [comment]
> do you want me to just directly make the changes for you

I'll be fine if you do that for me, but if you want me to do it, I can try.

**Review by SansPapyrus683 — APPROVED** [review]
@ryanchou-dev let's get this merged

**Review by ryanchou-dev — APPROVED** [review]
dubs!

**Pull request merged**
