### PR TITLE
New Problems

### PR DESCRIPTION
**Pull request by HarryWangATX**

### CODE REVIEW

**Comment by bqi343** [comment]
uhh let's not put silver problems in bronze ad hoc

**Comment by bqi343** [comment]
It seems odd to keep placing cycle problems in func graphs but idk where else

**Comment by HarryWangATX** [comment]
> uhh let's not put silver problems in bronze ad hoc (also, marking it as easier than the other problems is misleading)

What about intro to greedy?

**Comment by bqi343** [comment]
sure ig we can just dump all of silver greedy there :eyes:

**Comment by HarryWangATX** [comment]
> sure ig we can just dump all of silver non-sorting greedy there 👀

cool

**Pull request merged**
