### PR TITLE
Add an alternative to CF-Predictor in the contest resources page

### PR DESCRIPTION
**Pull request by xUser5000**
_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [x] I have tested my code
- [x] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [x] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

### CODE REVIEW

**Review by dutinmeow — APPROVED** [review]
Sure?

**Comment by xUser5000** [comment]
Yeah, I've tried it and I personally prefer it over CF-predictor. It gives much more useful information, does not lag, is accurate, and works so fast in realtime. So, I guess it's a good idea to add it to the resources.

**Comment by dutinmeow** [comment]
Maybe get a second opinion? Do you know anyone else who uses this extention?

**Comment by xUser5000** [comment]
SecondThread mentions he uses it [here](https://youtu.be/qUZgyNA5h_w?t=8168).

**Review by SansPapyrus683 — APPROVED** [review]
yeah, don't see any harm
i'll merge when this gets 1 more approval

**Review by dongliu0426 — APPROVED** [review]
🥕

**Pull request merged**
