### PR TITLE
Editorial for POI 16 Parade

### PR DESCRIPTION
**Pull request by dolphingarlic**

### CODE REVIEW

**Comment by bqi343** [comment]
> ($-1$ if $v$ is the root of the tree)

Why?

**Comment by dolphingarlic** [comment]
Because the root doesn't have a parent, so |C| = degree, but for each other node, |C| = degree - 1

**Comment by bqi343** [comment]
Why don't you write it in terms of degree then?

**Comment by dolphingarlic** [comment]
I think I just wanted to reuse C because it's shorter. I'll change it to be in terms of degree though

**Pull request merged**
