### PR TITLE
Content: Add language tags 

### PR DESCRIPTION
**Pull request by dliu426**
Remove c++ content when another language is selected.
- https://usaco.guide/bronze/intro-sets#inserting--deleting-keys-while-iterating

### CODE REVIEW

**Comment by thecodingwizard** [comment]
@nchn27 @andrewwangva are deleting keys an issue in Java? Or can we safely hide this section in Java?

**Comment by andrewwangva** [comment]
> @nchn27 @andrewwangva are deleting keys an issue in Java? Or can we safely hide this section in Java?

I'm pretty sure there's an error thrown when deleting items that are part of the collection when using an iterator(ever hidden iterators such as for-each loops). The only way to delete from collections while using iterators is using the iterator.remove() method if I remember correctly.

**Comment by andrewwangva** [comment]
> > @nchn27 @andrewwangva are deleting keys an issue in Java? Or can we safely hide this section in Java?
> 
> I'm pretty sure there's an error thrown when deleting items that are part of the collection when using an iterator(ever hidden iterators such as for-each loops). The only way to delete from collections while using iterators is using the iterator.remove() method if I remember correctly.

It talks a little about it in [this](https://usaco.guide/silver/intro-ordered) but maybe we should expand on it if needed?

**Comment by thecodingwizard** [comment]
okay sure. I'll merge this PR for now, but @andrewwangva can you add the corresponding Java section if you feel it's appropriate?

**Pull request merged**
