### PR TITLE
Update Divisibility.mdx

### PR DESCRIPTION
**Pull request by Pramad712**
Fix typo in LCM description

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [ x] I have tested my code.
- [ x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ x] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by envyaims** [comment]
i mean.. does this matter

**Comment by Pramad712** [comment]
LCF is always 1. LCM is not.

**Comment by envyaims** [comment]
> LCF is always 1. LCM is not.

LCF isnt a thing

**Comment by Pramad712** [comment]
I know. But saying "least common multiple is the smallest factor of both a
and b" is basically saying LCM = LCF (lcf meaning least common factor, aka
1)

**Comment by SansPapyrus683** [comment]
> The **least common multiple (LCM)** of two integers $a$ and $b$ is the smallest
integer divisible by both $a$ and $b$.

not sure where it says this?

**Pull request closed without merging**
