### PR TITLE
Add Python to Intro_Sorting.mdx

### PR DESCRIPTION
**Pull request by CryoJS**
Added Python code for library sorting on static arrays section. Links to #3444, but does not fully resolve the entire issue.

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [X] I have tested my code.
- [X] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [X] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Review by SansPapyrus683 — APPROVED** [review]

**Comment by SansPapyrus683** [comment]
is this used in cp? i've never touched `array` tbh

**Comment by CryoJS** [comment]
> is this used in cp? i've never touched `array` tbh

I've only used it in specific cases where you want to use less memory.
So pretty much only used for optimization/efficiency purposes (in cp).

**Comment by SansPapyrus683** [comment]
> less memory

wb time? is there a problem where `list` doesn't work but `array` does?

**Comment by CryoJS** [comment]
> wb time?

Arrays are slightly faster, but I haven't come across any applications yet. Python lists are constant time access too, so it's a small difference. Usually, I would just write in C++ if the problem's constraints are too strict (for Python).

But I do remember a question that I had to use arrays in (to save memory): https://dmoj.ca/problem/dp1p1 (16M memory limit).

**Pull request merged**
