### PR TITLE
added python solution for stick divisions

### PR DESCRIPTION
**Pull request by freakin23**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by freakin23** [comment]
Acceptance Proof:
Screenshot from 2024-05-17 22-01-13

**Review by SansPapyrus683 — APPROVED** [review]
alright show ss of updated code?

**Comment by freakin23** [comment]
Updated code??

**Comment by freakin23** [comment]
> alright show ss of updated code?

Oh i see you made some changes in for loop
Screenshot from 2024-05-18 09-00-00

**Comment by SansPapyrus683** [comment]
does it work

**Comment by freakin23** [comment]
> does it work

yes

**Comment by SansPapyrus683** [comment]
may i see proof?

**Comment by freakin23** [comment]
> may i see proof?

**Comment by SansPapyrus683** [comment]
to other CMs, this pr seems small enough that i think i can merge it myself

**Pull request merged**
