### PR TITLE
Add Cowntagion to IntroTrees

### PR DESCRIPTION
**Pull request by HarryWangATX**

### CODE REVIEW

**Comment by HarryWangATX** [comment]
rip project Automator broke.

**Comment by bqi343** [comment]
It's already in Bronze, we shouldn't have it in both modules.

https://usaco.guide/bronze/intro-graphs?lang=cpp

(difficulty might be off? :eyes:)

**Comment by HarryWangATX** [comment]
> It's already in Bronze and we shouldn't have it in both modules. Maybe remove it from Bronze?
> 
> 
> 
> https://usaco.guide/bronze/intro-graphs?lang=cpp
> 
> 
> 
> (difficulty might be off? :eyes:)

ywa i think tree is better

**Comment by HarryWangATX** [comment]
> (difficulty might be off? 👀)

also, is difficulty relative to division or just its raw difficulty

**Comment by bqi343** [comment]
> also, is difficulty relative to division or just its raw difficulty

it's relative to module

> (difficulty might be off? 👀)

specifically, I was referring to the other Bronze problems having higher difficulties

**Comment by HarryWangATX** [comment]
> specifically, I was referring to the other Bronze problems having higher difficulties

i see lmao. honestly, cowtagion was really ez tho...

**Review by bqi343 — CHANGES_REQUESTED** [review]
see above

**Comment by bqi343** [comment]
@HarryWangATX Should Grass Planting go in Silver as well?

**Comment by HarryWangATX** [comment]
> @HarryWangATX Should Grass Planting go in Silver as well?

I think bronze should be fine for grass planting.

**Review by bqi343 — APPROVED** [review]

**Pull request merged**
