### PR TITLE
Added USACO - 810 to the greedy section in Silver.

### PR DESCRIPTION
**Pull request by ismailfateen**
_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

I was wondering why it's not in the greedy section, In my honest opinion, it's one of the best Greedy problems to appear in Silver.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
there's enough greedy problems though

**Comment by dustin-miao** [comment]
If it's better than one of the existing ones it might be worth adding.

**Comment by SansPapyrus683** [comment]
then what should be moved to additional practice

**Comment by dustin-miao** [comment]
image

**Comment by SansPapyrus683** [comment]
It was also previously established in the discord that problems that don’t have enough space are moved there
If not, I’m establishing that now

**Pull request closed without merging**
