### PR TITLE
haybale stacking, grass planting

### LINKED ISSUE #606: Dead USACO problems
USACO Problems earlier than 2012 US Open seem to no longer accept Analysis Mode submissions.
[Some of these problems are used in USACO Guide](https://usaco.guide/plat/hld#problem-http://www.usaco.org/index.php?page=viewproblem2&cpid=102).

We should probably link to a mirror site such as [Luogu](https://www.luogu.com.cn/problem/P3038) or contact USACO staff.

### PR DESCRIPTION
**Pull request by bqi343**
closes #606

### CODE REVIEW

**Review by frodakcin — COMMENTED** [review]
It feels kinda out of place to have an extra link w/o context. Would it be better to wrap it in `Info` or `Warning`? Maybe we can add a footnote instead?

**Comment by HarryWangATX** [comment]
yea i think we should still put the warning there, but add the link inside of the warning

**Comment by frodakcin** [comment]
Actually I think a footnote would be very fitting here, although IDK if superscript is supported

**Comment by bqi343** [comment]
Idt you can add a footnote in the middle of a problem table though. @thecodingwizard what do you think?

**Comment by thecodingwizard** [comment]
Uhh this might be possible (I'm thinking we can add an "info" icon right after the problem name, and then when the user hovers over the icon (or click on mobile) they get a popup).

This might be a bit nontrivial to implement though (might need to modify problem constructor) -- would recommend just leaving it as a comment below the table for now

**Review by frodakcin — APPROVED** [review]

**Comment by frodakcin** [comment]
I'll wait for a secondary review, in case someone has a better idea

**Comment by bqi343** [comment]
looks fine, I'll just merge

**Pull request merged**
