### PR TITLE
Update MarkCompleteButton.tsx

### PR DESCRIPTION
**Pull request by MrinallU**
Allowed main option to show icon.

### CODE REVIEW

**Comment by thecodingwizard** [comment]
image

It looks a bit weird when it's not started... can we not have the blank space when it's not started?

image

the left padding might also need some adjustment.

Otherwise looks good, thanks! :)

**Comment by MrinallU** [comment]
Alright I'll work on that then.

**Comment by thecodingwizard** [comment]
@MrinallU anything I can do to help with this? :)

**Comment by MrinallU** [comment]
@thecodingwizard Are there any classNames that can help with this, as I am not finding anything.

**Comment by thecodingwizard** [comment]
@MrinallU maybe add `flex` to the `h3` tag surrounding the module progress text / dropdown? (might need to do some adjustments)

**Comment by MrinallU** [comment]
@thecodingwizard Nevermind I think I got it!

**Comment by MrinallU** [comment]
Capture
How's this?

**Comment by thecodingwizard** [comment]
Oops I didn't mean in the actual dropdown menu -- how it was before was fine. I meant in the dropdown menu button
image

**Comment by MrinallU** [comment]
I changed that too. 
My dropdown with Not Started:
Capture
Main Websites Dropdown:
Capture

**Comment by MrinallU** [comment]
I'm pretty sure mine and the websites maindropdown are the same and I will undo the Not Started dropdown item.

**Comment by thecodingwizard** [comment]
image

I mean the dropdown on the bottom of the module. The one on the top is fine :)

**Comment by thecodingwizard** [comment]
Seems like #400 implemented this...

**Pull request closed without merging**
