### PR TITLE
change text color from white to blue-900 while also fixing contrast

### PR DESCRIPTION
**Pull request by ethanjoby**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes. https://github.com/cpinitiative/usaco-guide/issues/4152
Screenshot 2024-02-22 at 7 18 44 PM

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
uh couldn't you have just made this as an addition to the og pr?

**Comment by ethanjoby** [comment]
That's mb. Any other changes needed?

**Comment by SansPapyrus683** [comment]
uh you'll have to ask @thecodingwizard about that, but after he approves i'll merge

**Review by danielzsh — APPROVED** [review]

**Comment by ethanjoby** [comment]
uh I was just wondering If I will get some kind of message or email when the interview is for the web developer position for usaco guide or who to contact for this.

**Pull request merged**
