### PR TITLE
minor rfc

### PR DESCRIPTION
**Pull request by freakin23**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

This way it looks much better.

### CODE REVIEW

**Comment by TheGamingMousse** [comment]
could you also remove the `using vi = vector<int>;` in the meantime?

**Comment by freakin23** [comment]
> could you also remove the `using vi = vector<int>;`?

it is being used in the code.

**Comment by TheGamingMousse** [comment]
> > could you also remove the `using vi = vector<int>;`?
> 
> it is being used in the code.

i mean like, change all occurrences of it to `vector<int>` lol

**Comment by freakin23** [comment]
> > > could you also remove the `using vi = vector<int>;`?
> > 
> > it is being used in the code.
> 
> i mean like, change all occurrences of it to `vector<int>` lol

Oh, my bad. 
Sure I will change it.

**Review by SansPapyrus683 — APPROVED** [review]

**Pull request merged**
