### PR TITLE
Added tuple information

### PR DESCRIPTION
**Pull request by KingWitherBrine**
added more tuple information.

### CODE REVIEW

**Comment by bqi343** [comment]
You can add tuples; just do `(1,)+([1,2,3],)`. Also, some of your parentheses / brackets / quotes don't match up.

**Comment by bqi343** [comment]
isn't most of this already included in the given link?

**Comment by KingWitherBrine** [comment]
Thank you, I changed it.

**Comment by bqi343** [comment]
should explain difference between immutable vs. mutable and why it's important

**Pull request closed without merging**
