### PR TITLE
add USACO Open 2023 Bronze FEB solution

### PR DESCRIPTION
**Pull request by thecodingwizard**
Todo: 
- Fix problem metadata
- Code conventions?

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

### CODE REVIEW

**Review by bqi343 — APPROVED** [review]
looks good. ~30 test cases seems like overkill though ...

**Comment by thecodingwizard** [comment]
Hm you're right, maybe I will add a note about not spending too much time on this

**Comment by SansPapyrus683** [comment]
yknow...i did it by making a brute force python script
maybe suggest that asw

**Comment by SansPapyrus683** [comment]
brute force is only described as a way to solve subtask 1
not as a way to gain insights into the patterns of the problems

**Comment by bqi343** [comment]
Sure, if you can't solve the test cases by hand then writing a brute-force solution first would help.

**Comment by SansPapyrus683** [comment]
> Sure, if you can't solve the test cases by hand then writing a brute-force solution first would help.

that...probably should've been put in the editorial...

**Comment by bqi343** [comment]
tbh if you can't brute force the test cases you're coming up with, you should come up with smaller test cases

**Pull request merged**
