### PR TITLE
some cses string hashing problem 

### PR DESCRIPTION
**Pull request by envyaims**
_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
don't we have enough of these

**Comment by envyaims** [comment]
> don't we have enough of these hashing problems

not enough cses and easier ones

**Comment by SansPapyrus683** [comment]
there's three easy problems right below the one you just added

**Comment by envyaims** [comment]
> there's three easy problems right below the one you just added

none of them are really beginner level like come on

**Comment by SansPapyrus683** [comment]
https://c.tenor.com/4SPXVRGXOroAAAAi/arknights-w-arknights.gif

**Comment by envyaims** [comment]
review or im sending clowns to your house tonight

**Comment by SansPapyrus683** [comment]
try me

**Comment by SansPapyrus683** [comment]
just kidding

**Review by ryanchou-dev — APPROVED** [review]
image

**Review by jjliewie — APPROVED** [review]

**Comment by envyaims** [comment]
@SansPapyrus683 get in here 🤡

**Comment by SansPapyrus683** [comment]
i told you, we have enough of these already

**Review by dongliu0426 — APPROVED** [review]

**Comment by envyaims** [comment]
> i told you, we have enough of these already

wheres the "very easy" string hashing problem?

**Comment by SansPapyrus683** [comment]
> also this teaches about the harmonic series which idt any other problem on the guide does so

it doesn't really "teach" more so as it does "oh yeah it magically works because of this"

> wheres the other "very easy" string hashing problem?

easy $\approx$ very easy, no real difference

**Comment by envyaims** [comment]
> > also this teaches about the harmonic series which idt any other problem on the guide does so
> 
> it doesn't really "teach" more so as it does "oh yeah it magically works because of this"
> 
> > wheres the other "very easy" string hashing problem?
> 
> easy ≈ very easy, no real difference

have you done the rated "easy"s?

**Comment by SansPapyrus683** [comment]
image
https://codeforces.com/contest/835/submission/136772934
https://codeforces.com/contest/1056/submission/115657246
yes, actually

**Comment by envyaims** [comment]
but are they as beginner friendly as this problem?

**Comment by SansPapyrus683** [comment]
yes

**Comment by ryanchou-dev** [comment]
you remind me of dustin ☺️

**Comment by jessechoe10** [comment]
> it doesn't really "teach" more so as it does "oh yeah it magically works because of this"

What??? Is it not intuitive how harmonic series works in this problem?
> easy ≈ very easy, no real difference

Not really... Very easy is the straight-up implementation of the algorithm, lol.

**Comment by jessechoe10** [comment]
> yes

:clown_face:

**Comment by SansPapyrus683** [comment]
> Not really... Very easy is the straight-up implementation of the algorithm, lol.

so is easy

**Comment by envyaims** [comment]
> > Not really... Very easy is the straight-up implementation of the algorithm, lol.
> 
> so is easy

Whats the downside of adding this problem? It's more basic hashing knowledge and introductory application in the long run. Censoring and the other cf problems are much harder than this.

**Comment by SansPapyrus683** [comment]
well, neither of us are gonna convince the other side at this rate
just get dong/maggie to merge

**Comment by ryanchou-dev** [comment]
tbh agree with envy, don't think there is that big of an issue with adding an easier problem + may make other ppl more encouraged

**Pull request merged**
