### PR TITLE
add support for hiding problem suggestion button

### PR DESCRIPTION
**Pull request by thecodingwizard**

### CODE REVIEW

**Review by HarryWangATX — APPROVED** [review]
🙏

**Comment by HarryWangATX** [comment]
actually i think itd be good if u disable the button and add a hover toolkit that says module is complete or smth like that

**Comment by andrewwangva** [comment]
> actually i think itd be good if u disable the button and add a hover toolkit that says module is complete or smth like that

wait it's only temporary so there's no need to add more.

**Comment by HarryWangATX** [comment]
> > actually i think itd be good if u disable the button and add a hover toolkit that says module is complete or smth like that
> 
> wait it's only temporary so there's no need to add more.

true

**Pull request merged**
