### PR TITLE
Copy problem URL to clipboard 

### PR DESCRIPTION
**Pull request by MrinallU**
Done and should be ready to merge.

### CODE REVIEW

**Comment by bqi343** [comment]
Is it possible to make "problem copied to clipboard" appear immediately when the URL is clicked (not when it's hovered over later?).

**Comment by MrinallU** [comment]
> Is it possible to make "problem copied to clipboard" appear immediately when the URL is clicked (not when it's hovered over later?).

The tooltip automatically disappeared when clicked and there is no option to make it appear onClick, only on hover so unfortunately I couldn't make it like that.

**Comment by MrinallU** [comment]
@bqi343 I also thought of adding toasts similar to how codeforces does it but I don't think thecodingwizard wants react toasts in the site.

**Comment by thecodingwizard** [comment]
Just implement toasts manually (or use react toasts or equivalent library and style with tailwind ui?)

**Comment by MrinallU** [comment]
@thecodingwizard https://www.creative-tim.com/learning-lab/tailwind-starter-kit/documentation/css/alerts found this

**Comment by MrinallU** [comment]
@bqi343 What if I changed the icon of the url onClick to a clipboard and then after a few seconds it will switch back to the normal icon?

**Comment by thecodingwizard** [comment]
I'm pretty sure there's a way to make the tooltip appear/disappear programmatically idk :/

**Comment by bqi343** [comment]
> @bqi343 What if I changed the icon of the url when clicked to a clipboard icon and then (to indicate success) and then after a few seconds it will switch back to the normal icon?

Sure.

Also ig I don't completely understand how React works. Is there a separate instance of `currProblemCopied` for each instance of `ProblemComponent`?

**Comment by bqi343** [comment]
Hm if I want to display "Problem already copied to clipboard!" only on the last copied problem, is this really the easiest way to do it?

https://dev.to/yezyilomo/global-state-management-in-react-with-global-variables-and-hooks-state-management-doesn-t-have-to-be-so-hard-2n2c

**Comment by thecodingwizard** [comment]
Typically you can just use a timeout of like 5 seconds instead? Otherwise you'll have to use some sketchy context or something :c

**Comment by MrinallU** [comment]
@thecodingwizard Got it.

**Comment by MrinallU** [comment]
@thecodingwizard Sorry I haven't been able to work on this all month, as I have many competitions I have to get ready for.

**Comment by bqi343** [comment]
reopen when ready ig

**Pull request closed without merging**
