### PR TITLE
Problem Suggestion: Add "Raisins" to Gold - Introduction to DP

### PR DESCRIPTION
**Pull request by jeffkmeng**
User `u5tnOwwl9vRItES9RAuv7i6CTwu2` suggested adding the problem [Raisins](https://oj.uz/problem/view/IOI09_raisins) to the `usacoEasy` table of the module [Gold - Introduction to DP](https://usaco.guide/gold/intro-dp#problemlist-usacoEasy).

**Automatically Generated JSON:**
```json
{
  "uniqueId": "ojuz-raisins",
  "name": "Raisins",
  "url": "https://oj.uz/problem/view/IOI09_raisins",
  "source": "oj.uz",
  "difficulty": "Hard",
  "isStarred": false,
  "tags": [
    "DP"
  ],
  "solutionMetadata": {
    "kind": "none"
  }
}
```
**Additional Notes**: None

*This PR was automatically generated from a user-submitted problem suggestion on the USACO guide.*

### CODE REVIEW

**Review by SansPapyrus683 — APPROVED** [review]
i call writing editorial for this (also might be suited for range dp instead of intro to dp)

**Comment by maggie-j-liu** [comment]
can we rename the table and heading since it doesn't just contain usaco problems?

**Comment by SansPapyrus683** [comment]
what would we rename it to then

**Comment by maggie-j-liu** [comment]
maybe just Introductory Problems?

**Comment by SansPapyrus683** [comment]
~~can you do that i have no idea how~~

**Review by dolphingarlic — CHANGES_REQUESTED** [review]
I think this problem should rather be "easy" or "normal"

**Pull request closed without merging**
