### PR TITLE
Functionality to show whether a problem has hints

### PR DESCRIPTION
**Pull request by akshatsinghania**
_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
  
  
  Added the feature to show if a problem has hints which was requested in this issue - https://github.com/cpinitiative/usaco-guide/issues/3650

### CODE REVIEW

**Comment by bqi343** [comment]
19A6AB4E-A76A-45E5-AF59-A647262CDD99

**Comment by bqi343** [comment]
Also, can you add `hasHints` to a problem with hints to test that it works correctly?

**Comment by akshatsinghania** [comment]
Fixed the typescript issue
Added hasHints to a problem with hints 
this one - https://usaco.guide/bronze/ad-hoc/?lang=cpp#problem-usaco-737

**Comment by SansPapyrus683** [comment]
looks great!
could you change it to hints + internal sol instead of internal sol + hints?

**Review by SansPapyrus683 — APPROVED** [review]
@bqi343 merge when you're ready

**Pull request merged**
