### PR TITLE
add python support to sets and maps

### PR DESCRIPTION
**Pull request by ryanchou-dev**
_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

### CODE REVIEW

**Comment by ryanchou-dev** [comment]
fixes #3675

**Comment by ryanchou-dev** [comment]
uhh wait sorry guys

**Comment by ryanchou-dev** [comment]
yo just to let y'all know, usaco.guide/editor seems to copy text wrong when there's a lot of lines (unless this is a problem with my computer)

**Comment by SansPapyrus683** [comment]
oh lol

**Pull request closed without merging**
