### PR TITLE
Update Func_Graphs.mdx

### LINKED ISSUE #882: Todo: Remove Dance Mooves, Swapity Swapity Swap from Func Graph
https://usaco.guide/silver/func-graphs?lang=cpp

Material discussed in the module isn't relevant for these problems.

### PR DESCRIPTION
**Pull request by bqi343**
Closes #882

### CODE REVIEW

**Review by frodakcin — APPROVED** [review]
Any reason double quotes are preferred over `\'`? (I had changed it like that to be consistent with the rest of the single quotes)

**Comment by frodakcin** [comment]
Actually why are we not always using double quotes?

**Comment by bqi343** [comment]
Whatever is fine, I think the autoformatter defaults to single quotes. unless single quote is contained in between.

**Comment by frodakcin** [comment]
I don't like autoformatter :(

I think it should default to double quote for all strings and only permit single quote for chars.

**Pull request merged**
