### PR TITLE
python solution for bracket seqeuences I

### PR DESCRIPTION
**Pull request by freakin23**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
please split into multiple prs

**Comment by freakin23** [comment]
> please split into multiple prs

done. you can check all.

**Review by SansPapyrus683 — APPROVED** [review]
show ac

**Comment by freakin23** [comment]
> show ac

Screenshot from 2024-08-11 20-03-06
Screenshot from 2024-08-11 20-02-59

**Pull request merged**
