### PR TITLE
FAQ

### PR DESCRIPTION
**Pull request by HarryWangATX**

### CODE REVIEW

**Comment by HarryWangATX** [comment]
@thecodingwizard do you think there are more questions to add? I'll try to think of some more but I'm pretty depleted.

**Comment by thecodingwizard** [comment]
these seem fine. What about contest scoring? would that be helpful?

**Comment by HarryWangATX** [comment]
@thecodingwizard i thought there is already a section on that. do uou want me to modify it?

**Comment by thecodingwizard** [comment]
Oops I totally missed that. Seems fine as is, thanks! :)

**Comment by HarryWangATX** [comment]
@thecodingwizard yea, no worries. i know you want an image, but i'm no good ta art. is there anything else you want to add?

**Comment by HarryWangATX** [comment]
@thecodingwizard Can you review this? thx

**Pull request merged**
