### PR TITLE
Made active problems/modules dropdowns

### PR DESCRIPTION
**Pull request by Vinceyou1**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Review by SansPapyrus683 — APPROVED** [review]

**Review by ryanchou-dev — COMMENTED** [review]
could you make it so that clicking the Active Problems/Modules box at all expands it?

also sus spacing on !open


looks cool though, tysm for ur work!

**Comment by mjh316** [comment]
I agree with ryan, just make the whole thing clickable!

**Comment by bqi343** [comment]
I'm confused about when you would want to hide your lists of active problems/modules. Aren't these the most important things on the dashboard page?

**Comment by mjh316** [comment]
> I'm confused about when you would want to hide your lists of active problems/modules. Aren't these the most important things on the dashboard page?

That's a good point - we had initially talked about it as having long lists that were blocking the new announcements, but we should be fine since announcements is being moved up. Apologies @Vinceyou1 !

**Pull request closed without merging**
