### PR TITLE
Add images for usaco-941

### PR DESCRIPTION
**Pull request by vivianhan404**

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
wait vivian can you copy paste the images here github's being an obnoxious female dog and i can't see them

**Comment by maggie-j-liu** [comment]
@SansPapyrus683 try this
image

**Comment by maggie-j-liu** [comment]
why are the images in a separate pr? (and why is the other pr closed?)

**Comment by SansPapyrus683** [comment]
k thx

**Comment by vivianhan404** [comment]
@maggie-j-liu I wasn't sure what you meant by doing a 'git pull' in order to avoid the code from reverting back, and I realized it was a really big mess with all three problems together in one pull request. So I kinda started over, made the edits on my branch, and I'm planning to send the problems one at a time. I wanted to merge the images first so I could put the correct permalinks into the editorial.

**Comment by maggie-j-liu** [comment]
ok, that's fine!
the images' links are relative to the file, so it's okay to add them in the same pull request (but this is fine too?)
by `git pull`, i mean that you probably made changes from the github website (by clicking commit suggestion), but these changes were not reflected on your local branch. `git pull` will sync your local branch so that the next time you push, the changes you made on the website won't be overwritten

**Pull request closed without merging**
