### PR TITLE
Monthly Table Revamp

### PR DESCRIPTION
**Pull request by bqi343**
`/general/usaco-monthlies`

Add some tags, allow showing all problems.

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [x] I have tested my code
- [x] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [x] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

### CODE REVIEW

**Review by jessechoe10 — APPROVED** [review]
Looks good to me.

**Comment by nwatx** [comment]
not sure why the gold solve shows as 100%, but the other months seem ok

**Comment by bqi343** [comment]
wdym?

**Comment by nwatx** [comment]
image

the solve rates were just all 100% (or close to it)

**Comment by bqi343** [comment]
This is intended behavior (try hovering over "Percent")

**Comment by nwatx** [comment]
yeah, it's good, just wanted to make sure because the other months generally did not have 'all green' solve rates.

**Pull request merged**
