### PR TITLE
content: add f-string warning

### PR DESCRIPTION
**Pull request by dliu426**

### CODE REVIEW

**Comment by bqi343** [comment]
I don't think we need to include this. f-strings have been around since python 3.6 but USACO uses python 3.4.

**Comment by dliu426** [comment]
Yeah, thats true. Just thought people would get confused because there were some python code [here](https://usaco.guide/bronze/intro-sorting#dynamic-arrays-of-pairs--tuples) that used f-strings.

**Comment by bqi343** [comment]
can't hurt

**Comment by dongliu0426** [comment]
ah now this has to be reverted

**Pull request merged**
