### PR TITLE
class, contest, and workshop announcements

### PR DESCRIPTION
**Pull request by mjh316**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [ x] I have tested my code.
- [ x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ x] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
image

3 banners :skull:

**Review by SansPapyrus683 — APPROVED** [review]
looks poggers

**Comment by thecodingwizard** [comment]
btw, we could consider making prettier banners: https://tailwindui.com/components/marketing/elements/banners

**Comment by mjh316** [comment]
Going to merge temporarily until we get announcements out (so we don't delay advertising any further)

**Comment by mjh316** [comment]
> btw, we could consider making prettier banners: https://tailwindui.com/components/marketing/elements/banners

If you could ship the components you like.... 😂

**Pull request merged**
