### PR TITLE
Added table and info about shorts/unsigned numbers

### PR DESCRIPTION
**Pull request by iEPei**

### CODE REVIEW

**Review by brad182 — APPROVED** [review]

**Comment by nathangong** [comment]
Could you create different tables for each language including java and python?

**Review by nathangong — CHANGES_REQUESTED** [review]
^

**Comment by nathangong** [comment]
@iEPei can you fix the errors with deployment? You can debug what's wrong by pasting the code into [usaco.guide/editor](https://usaco.guide/editor).

**Comment by iEPei** [comment]
yeah the usaco guide editor is kinda finicky, it keeps black screening but i think this should work

**Review by HarryWangATX — CHANGES_REQUESTED** [review]
can u wrap the types in inline code

**Comment by iEPei** [comment]
OK, I just did so

**Review by nwatx — APPROVED** [review]

**Review by nathangong — APPROVED** [review]

**Review by dongliu0426 — APPROVED** [review]
0: nice

**Pull request merged**
