### PR TITLE
fix broken link

### PR DESCRIPTION
**Pull request by Farrius**
Just fixed the broken link.

### CODE REVIEW

**Comment by bqi343** [comment]
Fix merge conflicts too :)

**Comment by dolphingarlic** [comment]
How are there already merge conflicts even though only one line changed 🤔

**Comment by Farrius** [comment]
I don't understand what happen, but should be fine :)

**Review by dongliu0426 — APPROVED** [review]

**Comment by jeffreymeng** [comment]
um what
who approved this??

**Pull request merged**
