### PR TITLE
a couple videos

### PR DESCRIPTION
**Pull request by envyaims**
_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
can you test these to make sure they get ac

**Comment by envyaims** [comment]
> can you test these to make sure they get ac also convert to tabs do that and i'll merge

converted to tabs

also dont they already test it in the videos?

**Comment by SansPapyrus683** [comment]
you never know

**Comment by envyaims** [comment]
> you never know

how about just merge :D

**Comment by SansPapyrus683** [comment]
do you want the hoodie or not

**Comment by envyaims** [comment]
aaaaaaaa this is so extra

**Pull request merged**
