### PR TITLE
FAQ

### PR DESCRIPTION
**Pull request by HarryWangATX**

### CODE REVIEW

**Comment by thecodingwizard** [comment]
Can you update the get help part and change it from discord server to forum?

And also instead of discourse comments link to forum instead.

Thanks!

**Comment by HarryWangATX** [comment]
Yea, I can fix that with the next commit. Are the questions I added the direction you want to go with SEO optimization?

**Comment by thecodingwizard** [comment]
Yeah, seems fine. Whatever you think people are likely to search :)

Oh, also maybe a part about classes https://forum.usaco.guide/t/usaco-classes-vs-self-studying-with-usaco-guide/335

Whatever you think is good!

**Comment by HarryWangATX** [comment]
K

**Comment by HarryWangATX** [comment]
Oops, just realized i merged to the wrong branch. Ill close this and create a pr to faq next commit

**Pull request closed without merging**
