### PR TITLE
fix: string_search

### LINKED ISSUE #4115: Contact Form Submission - Minor Mistake (string-search)
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard/
**Module**: string-search
**Topic**: Minor Mistake
**Message**: 
the coincides with
->
that coincides with

### PR DESCRIPTION
**Pull request by shubhamku044**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes #4115

### CODE REVIEW

**Comment by shubhamku044** [comment]
#4118

**Comment by shubhamku044** [comment]
#4115

**Comment by devo1ution** [comment]
Could you link to the issue by writing "Closes #4115" in your pr description? Thanks!

**Review by devo1ution — APPROVED** [review]

**Comment by shubhamku044** [comment]
> Could you link to the issue by writing "Closes #4115" in your pr description? Thanks!

done

**Pull request merged**
