### PR TITLE
Update Meet_In_The_Middle.mdx for Python equivalent code

### PR DESCRIPTION
**Pull request by falconboi12**
Added the python implementation

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by freakin23** [comment]
use annotations

**Comment by freakin23** [comment]
Have you ever compiled your code? 
Your code is giving TLE for most of the TCs.  Plus you wrote a wrong function name.

**Comment by envyaims** [comment]
can you show AC code? i remember trying to write a python sol when i initially wrote the module but it timed out on cses

**Comment by SansPapyrus683** [comment]
yeah for sols like this you might as well just submit it under user solutions

**Comment by freakin23** [comment]
> My bad. I jumped the gun on the implementation, will get back on improving it before submitting a PR

I don't think it can be improved, the tight constraints in CSES is not very good for python

**Pull request closed without merging**
