### PR TITLE
Update Conclusion.problems.json

### PR DESCRIPTION
**Pull request by Pramad712**
(Move to functional graphs section, it has only 3 problems)

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x ] I have tested my code.
- [x ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x ] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by Pramad712** [comment]
see https://github.com/cpinitiative/usaco-guide/pull/4064 for the pull request that goes with this (and actually adds the problem)

**Comment by SansPapyrus683** [comment]
wait does this pr just...delete a problem?

**Comment by Pramad712** [comment]
It was meant to be an add-on to the pull request to put it in the
functional graphs

**Comment by SansPapyrus683** [comment]
just put everything in the other pr

**Pull request closed without merging**
