### PR TITLE
cf-1914C - Solution codes added in Java and Python

### PR DESCRIPTION
**Pull request by Audacity21**
Added solution codes for [cf-1914C](https://usaco.guide/problems/cf-quests/solution) in Java and python as it was missing. 

Linking my accepted solutions of the question from codeforces below: 

Java accepted solution: https://codeforces.com/problemset/submission/1914/267802583
Python accepted solution: https://codeforces.com/problemset/submission/1914/267802332

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
~~- [ ] I have linked this PR to any issues that it closes.~~

This is my first time contributing to this project. Let me know if I have to change anything.

### CODE REVIEW

**Comment by Audacity21** [comment]
Not sure why one of the test failed. Need help with that.

**Review by SansPapyrus683 — CHANGES_REQUESTED** [review]
will sansify later, op if you wanna make this easier:
1. place the python section after the java section
2. make the code consistent w/ the c++ version

**Comment by SansPapyrus683** [comment]
if you wanna keep ur og sols, just submit them under user solutions

**Comment by SansPapyrus683** [comment]
NEVERMIND I WAS TOO HARSH IT SEEMS YOUR CODE IS CONSISTENT MY FAULT MY FAULT

**Review by SansPapyrus683 — APPROVED** [review]

**Comment by SansPapyrus683** [comment]
this is just a lang tl so i'll merge

**Pull request merged**
