### PR TITLE
py sol for Mail Delivery

### PR DESCRIPTION
**Pull request by freakin23**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

AC: https://cses.fi/paste/71d790740a105f2ba6235e/

### CODE REVIEW

**Review by SansPapyrus683 — APPROVED** [review]
can you see if it still acs

**Comment by freakin23** [comment]
> can you see if it still acs

https://cses.fi/paste/9f9192513396792fa639d9/

**Comment by SansPapyrus683** [comment]
i...can't see the result

**Comment by freakin23** [comment]
> i...can't see the result

Screenshot from 2024-10-18 10-48-28
Screenshot from 2024-10-18 10-48-36

**Pull request merged**
