### PR TITLE
Added myself as content author :-)

### PR DESCRIPTION
**Pull request by AAkashyap1**

### CODE REVIEW

**Comment by ryanchou-dev** [comment]
your name also goes on the github readme :)

**Comment by AAkashyap1** [comment]
> your name also goes on the github readme :)

wait how do i update that

**Comment by ryanchou-dev** [comment]
usaco-guide/README.md

**Comment by AAkashyap1** [comment]
> usaco-guide/README.md (there's no subfolders)

actually wait im still there

**Comment by ryanchou-dev** [comment]
i didn't see that, my bad.

**Review by ryanchou-dev — APPROVED** [review]
👍

**Comment by dongliu0426** [comment]
cool

**Pull request merged**
