### PR TITLE
add this cow photo

### PR DESCRIPTION
**Pull request by sathu-beep**
pls

### CODE REVIEW

**Comment by tachithanhdanh** [comment]
nice

**Review by HarryWangATX — CHANGES_REQUESTED** [review]
rename file name pls

**Review by tachithanhdanh — APPROVED** [review]
I have no idea why the file is emty 👀

**Comment by thecodingwizard** [comment]
github claims file is empty because it has no lines of code. But the image is there and is uploaded correctly (other than naming)

**Review by HarryWangATX — APPROVED** [review]

**Pull request merged**
