### PR TITLE
Fix template link

### PR DESCRIPTION
**Pull request by dongliu0426**

### CODE REVIEW

**Comment by thecodingwizard** [comment]
@bqi343 should we use the new one?

**Comment by bqi343** [comment]
either should work. My current template is not C++11 compatible, previous one is

**Review by thecodingwizard — CHANGES_REQUESTED** [review]
@dongliu0426 can we update to the new template then?

- update link in content documentation
- update snippet here: https://github.com/cpinitiative/usaco-guide/blob/master/src/mdx-plugins/rehype-snippets.js
- any other changes?

**Comment by thecodingwizard** [comment]
seems fine I hope

**Pull request merged**
