### PR TITLE
Code Snips: modify design (is this better?)

### PR DESCRIPTION
**Pull request by frodakcin**

### CODE REVIEW

**Comment by frodakcin** [comment]
@HarryWangATX Do you think this looks better?

**Comment by frodakcin** [comment]
wait where did my changes go

**Comment by HarryWangATX** [comment]
wait so from my understanding u put the code in {} brackets right?

**Comment by frodakcin** [comment]
Wait no nvm I made it so only top and bottom show arrows but apparently the changes got reverted..... idk what happ[ened

**Comment by HarryWangATX** [comment]
oh hmm prob cus of the merge...

**Comment by frodakcin** [comment]
https://github.com/cpinitiative/usaco-guide/commit/c0bdb31f0e4fece677a2d660cf8bdbed4653b5a5

right here.

**Comment by frodakcin** [comment]
guess it got merged away :/

**Comment by HarryWangATX** [comment]
k lemme test it out

**Comment by HarryWangATX** [comment]
wait i cant oops. it got reverted

**Comment by HarryWangATX** [comment]
code looks fine to me

**Comment by frodakcin** [comment]
I just copied it back... you can test it on next deployment

**Comment by HarryWangATX** [comment]
alr

**Review by HarryWangATX — APPROVED** [review]

**Comment by HarryWangATX** [comment]
looks good!

**Comment by frodakcin** [comment]
ngl I like the other way better :eyes: because it provides a clearer distinction

**Comment by HarryWangATX** [comment]
> ngl I like the other way better 👀 because it provides a clearer distinction

👀 rly?? i was rly annoyed at the arrows lol

**Comment by HarryWangATX** [comment]
but i think most IDEs just do one arrow on top

**Comment by frodakcin** [comment]
Anyone else have opinion?

**Comment by thecodingwizard** [comment]
Either way is fine by me; I don't see people expanding snippets too often anyway :P

**Comment by frodakcin** [comment]
If code is reasonable then yea, it should be ready for merge

**Pull request merged**
