### PR TITLE
Sathu beep patch 3

### PR DESCRIPTION
**Pull request by sathu-beep**

### CODE REVIEW

**Comment by dongliu0426** [comment]
same as #1781 ?

**Comment by sathu-beep** [comment]
> same as #1781 ?

no its not check the adding_solution.mdx file

**Comment by dongliu0426** [comment]
> > same as #1781 ?
> 
> no its not check the adding_solution.mdx file

yes, i checked. it's identical

**Comment by HarryWangATX** [comment]
its the same lmao

**Pull request closed without merging**
