### PR TITLE
Bitwise operators & SOS dp

### PR DESCRIPTION
**Pull request by frodakcin**

### CODE REVIEW

**Comment by thecodingwizard** [comment]
Maybe we should link to that module in Bronze Complete Search with Recursion? And add a note that it's not required for bronze. https://usaco.guide/bronze/complete-rec#generating-subsets-with-bitmasks

**Comment by thecodingwizard** [comment]
also is knowing how to do addition / multiplication with bitwise operators really necessary...?

**Comment by frodakcin** [comment]
Sure, I just thought it was a nice way to use/check understanding of bitwise operations. Other examples (like bitmask dp) are more complex and need to be in the context of an example problem.

**Comment by thecodingwizard** [comment]
okay, sounds good. I'll add a note and merge :)

**Pull request merged**
