### PR TITLE
Cses 1081

### PR DESCRIPTION
**Pull request by 876pol**
_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

### CODE REVIEW

**Comment by 876pol** [comment]
Old PR: https://github.com/cpinitiative/usaco-guide/pull/3305
idk why but it got deleted when i tried to resync it with master

**Comment by SansPapyrus683** [comment]
nonono

**Comment by 876pol** [comment]
merge?

reply to comment made on previous closed pr ([link](https://github.com/cpinitiative/usaco-guide/pull/3305#discussion_r1102228971)): 
- it doesn't let me compile if i remove the static keyword

**Review by SansPapyrus683 — CHANGES_REQUESTED** [review]
oops what

**Review by SansPapyrus683 — APPROVED** [review]
@envyaims @ryanchou-dev

**Review by ryanchou-dev — APPROVED** [review]
ac orz

**Pull request merged**
