### PR TITLE
jesus christ

### PR DESCRIPTION
**Pull request by SansPapyrus683**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
@bqi343 review?

**Review by bqi343 — CHANGES_REQUESTED** [review]
20 should actually be 19 everywhere in the module

**Comment by SansPapyrus683** [comment]
where

**Comment by bqi343** [comment]
in the solution I mean

everywhere

**Review by ryanchou-dev — DISMISSED** [review]

**Comment by bqi343** [comment]
my comment was not addressed

**Comment by SansPapyrus683** [comment]
1. $K \le 20$ is basically $K \leq 19$
2. "20 is a good cutoff" this really depends on what you mean by cutoff, and most people think 20 would be the more appropriate number to use in this situation

**Comment by bqi343** [comment]
then please write $K<20$ instead of $K\le 20$

**Review by bqi343 — CHANGES_REQUESTED** [review]
I'm confused about why the analysis switches between lowercase and uppercase N. Same for K.

**Comment by SansPapyrus683** [comment]
LMAO I THOUGHT \le WAS <

**Comment by SansPapyrus683** [comment]
anyways it only uses uppercase in the complexity
but i changed it for you

**Review by bqi343 — APPROVED** [review]
uppercase K, N would make more sense considering that that's the way it is in the problem statement but ok

**Pull request merged**
