### PR TITLE
Add a difficulty to Maximizing Productivity

### PR DESCRIPTION
**Pull request by idk-12345678**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [X ] I have tested my code.
- [X ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [X ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ X] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Review by envyaims — APPROVED** [review]
in 2018 this would be normal but if the guide was written to modern standards it would be easy or very easy lmao

**Comment by idk-12345678** [comment]
it nah definitly not very easy, its like borderline easy-normal but i put it normal

**Comment by bqi343** [comment]
this difficulty doesn't show up anywhere so there's no point in changing it

**Comment by idk-12345678** [comment]
Its in usaco monthlies. Also we merged it like 4 months ago

**Comment by bqi343** [comment]
But difficulty is not displayed in the monthlies page.

> Its in usaco monthlies. Also we merged it like 4 months ago

Just wanted to note that there would be no point in creating additional PRs like this.

**Pull request merged**
