### PR TITLE
Problem Suggestion: Add "MST Unification" to Gold - Additional Practice for USACO Gold

### PR DESCRIPTION
**Pull request by maggieliu05**
User `xHulKemIumPANuvaYFIXtNRlsz63` suggested adding the problem [MST Unification](https://codeforces.com/contest/1108/problem/F) to the `problems` table of the module [Gold - Additional Practice for USACO Gold](https://usaco.guide/gold/gold-conclusion#problemlist-problems).

**Automatically Generated JSON:**
```json
{
  "uniqueId": "cf-1108F",
  "name": "MST Unification",
  "url": "https://codeforces.com/contest/1108/problem/F",
  "source": "CF",
  "difficulty": "Normal",
  "isStarred": false,
  "tags": [
    "DSU",
    "MST"
  ],
  "solutionMetadata": {
    "kind": "autogen-label-from-site",
    "site": "CF"
  }
}
```
**Additional Notes**: None

*This PR was automatically generated from a user-submitted problem suggestion on the USACO guide.*

### CODE REVIEW

**Review by envyaims — APPROVED** [review]
clownsans

**Comment by ivaziva** [comment]
???

**Review by ryanchou-dev — APPROVED** [review]
cool problem!

**Comment by ivaziva** [comment]
will it be posted soon?

**Pull request merged**
