### PR TITLE
changed z-index of navbar

### PR DESCRIPTION
**Pull request by RealMyth21**
_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [x] I have tested my code
- [x] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [x] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

### CODE REVIEW

**Comment by nathangong** [comment]
image

for some reason the usaco guide title is now in front of the drop down

**Comment by nathangong** [comment]
^ this is probably because the USACO Guide title also has a z-index of 10

**Comment by nathangong** [comment]
I haven't throughly tested yet, but I found a potential fix:
image
adding the z-0 property for the div on line 73 allows the nav bar dropdowns to display above the "Usaco Guide" message while still enabling the glow feature to be under the text.

**Comment by RealMyth21** [comment]
I tried just changing it from z-20 to z-15. It seems to work for me.

**Comment by RealMyth21** [comment]
Tailwind only supports certain z indexes which are multiples of 10. Earlier, I tried using z-20, which messed up the thing you talked about earlier, so then I changed it to z-15, thinking that it was in the middle. It worked perfectly! BUT THE THING IS, it doesn't exist so it didn't apply any changes. This means it was perfect without changes to the z-index, so I removed it. It seems to work fine. Please check it out!

**Comment by nathangong** [comment]
Looks good! For some reason there's a failing build test
image
I doubt it's related to this PR, @maggie-j-liu do you know what's going on here?

**Comment by maggie-j-liu** [comment]
i think i fixed it, try merging master into your branch and see if it passes now

**Pull request merged**
