### PR TITLE
Update Tree_Euler.problems.json

### PR DESCRIPTION
**Pull request by MariaChrysafis**
added new problem

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

(My first pull request, idk how this works. I have no code, just a problem proposition; since parenthesization is like an Euler tour of a tree, you can think of the problem as trees.)

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

### CODE REVIEW

**Comment by envyaims** [comment]
i dont think euler tour is really necessary no?

**Comment by SansPapyrus683** [comment]
> since parenthesization is like an Euler tour of a tree, you can think of the problem as trees

apparently this is their reasoning

**Comment by MariaChrysafis** [comment]
> i dont really get why this is euler tour... I think it's stacks/dfs + greedy at most.

Yeah, it's a bit of a stretch. But one solution is to think of parenthesization of as an Euler tour of a forest. Then, the cost function is just the sum of the depths of all nodes in the tree. Moving a bracket optimally is equivalent to extracting a node from the forest and making it its own connected component (this decreases the cost of the forest by the subtree size). Therefore, the problem is actually asking us to find the k largest subtrees in the forest and to remove them.

**Comment by envyaims** [comment]
I'm sorry but there are a lot of other problems out there that fits the category a lot better. This problem isn't bad or anything, but I fail to see something like finding the k largest subtrees in the forest really fits with the euler tour ideology

**Pull request closed without merging**
