### PR TITLE
Fix modal bug

### PR DESCRIPTION
**Pull request by MrinallU**

### CODE REVIEW

**Comment by MrinallU** [comment]
And I don't think decreasing the z index changes anything.

**Comment by thecodingwizard** [comment]
@MrinallU it makes the scrollbar look a bit off, and might be messy on mobile too. I don't think `inset-0` is a good solution (if we wanted to change the position of the modal, we should use padding, not inset).

If increasing the z-index doesn't fix it, it's possible there's some stacking context issue: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

**Comment by MrinallU** [comment]
@thecodingwizard How's this?

**Comment by thecodingwizard** [comment]
@MrinallU I meant on the dashboard page

**Comment by MrinallU** [comment]
@thecodingwizard How do I get the announcement to show up on my side?

**Pull request closed without merging**
