### PR TITLE
CSES Subarray Divisibility, CPP sol

### PR DESCRIPTION
**Pull request by HarryWangATX**

### CODE REVIEW

**Comment by bqi343** [comment]
Looks like there's a mistake when I render with liveupdate. Also,

> I think you should split the explanation into separate paragraphs to make it a bit easier to read

This includes putting some of the equations on separate lines:

```
$$
equation
$$
```

Also use $\cdot$ instead of $*$, and use $\texttt{}$ around variable names.

**Comment by HarryWangATX** [comment]
@bqi343 do you know why the links are failing? I don't think I changed any links.

**Comment by bqi343** [comment]
Try pasting it into liveupdate.

**Comment by HarryWangATX** [comment]
K i saw an rendering error

**Comment by HarryWangATX** [comment]
@bqi343 i think i fixed everything, lmk if I need to edit more.

**Comment by HarryWangATX** [comment]
looks nice!

**Pull request merged**
