### PR TITLE
py sol for usaco-858

### PR DESCRIPTION
**Pull request by freakin23**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

AC: 
Screenshot from 2024-12-01 12-48-41

### CODE REVIEW

**Review by SansPapyrus683 — APPROVED** [review]
check again and i'll merge

**Comment by freakin23** [comment]
> check again and i'll merge
Screenshot_2024-12-01-23-56-47-65_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by SansPapyrus683** [comment]
how did bro submit on mobile??

**Comment by freakin23** [comment]
> how did bro submit on mobile??

All you need is a compiler app

**Pull request merged**
