### PR TITLE
Problem Suggestion: Add "Array Destruction" to Silver - More Operations on Ordered Sets

### PR DESCRIPTION
**Pull request by jeffkmeng**
User `7AF1MKJjqmXfBDGhimSWEhXqe8k1` suggested adding the problem [Array Destruction](https://codeforces.com/problemset/problem/1474/C) to the `general` table of the module [Silver - More Operations on Ordered Sets](https://usaco.guide/silver/intro-ordered#problemlist-general).

**Automatically Generated JSON:**
```json
{
  "uniqueId": "cf-1474C",
  "name": "Array Destruction",
  "url": "https://codeforces.com/problemset/problem/1474/C",
  "source": "CF",
  "difficulty": "Normal",
  "isStarred": false,
  "tags": [
    "Multiset",
    "Sorting",
    "Greedy"
  ],
  "solutionMetadata": {
    "kind": "autogen-label-from-site",
    "site": "CF"
  }
}
```
**Additional Notes**: None

*This PR was automatically generated from a user-submitted problem suggestion on the USACO guide.*

### CODE REVIEW

**Review by jessechoe10 — APPROVED** [review]

**Comment by SansPapyrus683** [comment]
maybe "greedy with sorting" would be better, but i guess it counts as ops on ordered sets?

**Comment by jessechoe10** [comment]
> maybe "greedy with sorting" would be better, but i guess it counts as ops on ordered sets?

Why? The hardest part about this problem is the operations with `std:multiset`.

**Comment by SansPapyrus683** [comment]
no, not really, any schmuck can do some iterator magic- the hardest part is the initial observation imo

**Comment by jessechoe10** [comment]
> schmuck

lol

**Comment by SansPapyrus683** [comment]
anyways, i call writing an editorial for this problem

**Review by SansPapyrus683 — APPROVED** [review]

**Comment by jessechoe10** [comment]
> anyways, i call writing an editorial for this problem

You can write the editorial, and I can write the C++ code.

**Pull request merged**
