### PR TITLE
Add cowmbat to problem list

### PR DESCRIPTION
**Pull request by dongliu0426**
- https://usaco-guide-git-dliu426-patch-11.cpinitiative.vercel.app/gold/intro-dp#harder-usaco

### CODE REVIEW

**Comment by frodakcin** [comment]
Looks good. 
While you're there, I find it kinda ironic the "Harder USACO" problems are labelled "Normal." Perhaps we can label the section "Additional Problems" instead.

**Comment by thecodingwizard** [comment]
Can you do this problem without Floyd Warshall's? That's not introduced at this point yet...

**Comment by dongliu0426** [comment]
dfs+dp instead?

**Comment by thecodingwizard** [comment]
can we include a note mentioning that you can do it w/o Floyd Warshall's? I think (?) the editorial only explains the floyd warshall solution, so people may be confused?

**Comment by bqi343** [comment]
I increased most of the difficulties (maybe not so accurate though). 

I think it's fine since Floyd-Warshall isn't required (and it isn't a big part of the solution). You can add a note if you want :)

**Pull request merged**
