### PR TITLE
Add Java Implementation to USACO Mountains

### PR DESCRIPTION
**Pull request by TruaShamu**

### CODE REVIEW

**Comment by maggie-j-liu** [comment]
Please use the [live editor](https://usaco.guide/liveupdate/) to check that your solution renders correctly before submitting a pull request.

**Comment by TruaShamu** [comment]
Sorry, I'll remember to do that next time.

**Review by dongliu0426 — APPROVED** [review]
add your name to the author list (oops i meant to request changes)

**Review by frodakcin — APPROVED** [review]
yea this looks fine

**Review by dongliu0426 — APPROVED** [review]

**Pull request merged**
