### PR TITLE
Update Greedy.mdx

### PR DESCRIPTION
**Pull request by tachithanhdanh**

### CODE REVIEW

**Comment by bqi343** [comment]
Can you do this in the other PR?

**Comment by tachithanhdanh** [comment]
What do you mean?

**Comment by bqi343** [comment]
Do this in #568 instead.

**Comment by tachithanhdanh** [comment]
I can do that?

**Comment by tachithanhdanh** [comment]
Sorry because I still don't quite understand the way of using github pull request properly

**Comment by bqi343** [comment]
Commit to the existing pull request instead of making a new one.

**Pull request closed without merging**
