### PR TITLE
one must imagine ks happy

### PR DESCRIPTION
**Pull request by SansPapyrus683**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Review by ryanchou-dev — APPROVED** [review]
one must imagine ryan satisfied

**Comment by SansPapyrus683** [comment]
ryan i thought you said you'd make the quiz

**Comment by ryanchou-dev** [comment]
> ryan i thought you said you'd make the quiz

im out on a trip rn -- ill do it monday

**Comment by SansPapyrus683** [comment]
ily ❤️

**Pull request merged**
