### PR TITLE
Quizzes

### PR DESCRIPTION
**Pull request by thecodingwizard**

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
image
these aren't going to be actual questions right

**Comment by maggie-j-liu** [comment]
I think that's just an example for the working w/ mdx module

**Comment by SansPapyrus683** [comment]
here we see the programmer in its natural environment, crying as they try to do something, anything to get the build working again

**Comment by thecodingwizard** [comment]
Legend says if this final commit doesn't work, the programmer will quit programming to become a cook.

image

**Comment by HarryWangATX** [comment]
> Legend says if this final commit doesn't work, the programmer will quit programming to become a cook.
> 
> image

LMAO fax

**Comment by HarryWangATX** [comment]
LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOL RIP NATHAN

**Comment by SansPapyrus683** [comment]
but if the build does work the quizzes be lookin damn fine

**Comment by HarryWangATX** [comment]
F in chat.

**Comment by nwatx** [comment]
> Legend says if this final commit doesn't work, the programmer will quit programming to become a cook.
> 
> image

unfortunately the commit did not work :laughing:

**Comment by SansPapyrus683** [comment]
wait did nathan just try building again lmao

**Comment by HarryWangATX** [comment]
mans desperate

**Review by jessechoe10 — APPROVED** [review]

**Review by SansPapyrus683 — APPROVED** [review]

**Comment by sathu-beep** [comment]
I will make a quiz for something tell me what needs work other than time complexity since I suck at that

**Pull request merged**
