### PR TITLE
Solution for CSES - 1075

### PR DESCRIPTION
**Pull request by dustin-miao**
_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
dustin didn't i literally say
to ask in the discord before adding a problem

**Comment by dutinmeow** [comment]
that's not how open source works

**Review by ryanchou-dev — APPROVED** [review]
yessir

**Review by bqi343 — COMMENTED** [review]
move the solution to the correct folder

**Review by dongliu0426 — APPROVED** [review]

**Pull request merged**
