### PR TITLE
Update Binary_Search.mdx

### PR DESCRIPTION
**Pull request by MinEuler**
I've added a worth solving problem ;)

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
hi! usually when adding a problem we add the solution as a separate page, not usually in the module, as that's where the _main_ examples are
unless you think there's something particularly notable about this problem?

**Comment by MinEuler** [comment]
Hi ! , I just wanted to contribute (as I think the problem is worth
solving) :)

‫في الأربعاء، 28 أغسطس 2024 في 7:20 ص تمت كتابة ما يلي بواسطة ‪Kevin
Sheng‬‏ ***@***.***‬‏>:‬

**Comment by SansPapyrus683** [comment]
yeah if that's the case i think it's better that you add it as a practice one w/ a solution
also deployment is failing

**Review by ryanchou-dev — CHANGES_REQUESTED** [review]
hi! thanks for contributing.

there are a few issues with your PR right now. (namely, no metadata, needing to add a separate solution page, and finding a good area for your problem)

we recommend that you read through our contributing section first! [https://usaco.guide/general/contributing](https://usaco.guide/general/contributing)

**Pull request closed without merging**
