### PR TITLE
Update String_Hashing.problems.json

### PR DESCRIPTION
**Pull request by ar492**
Added a problem

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [x] I have tested my code
- [x] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [x] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

### CODE REVIEW

**Comment by dongliu0426** [comment]
I don't see a point in adding this problem. It's exactly the same as the focus problem (https://dmoj.ca/problem/ccc20s3).

**Comment by ar492** [comment]
> I don't see a point in adding this problem. It's exactly the same as the focus problem (https://dmoj.ca/problem/ccc20s3).

They are not the same; the focus problem deals with permutations

**Comment by SansPapyrus683** [comment]
i mean the essence is basically the same- using hashing for comparing strings
focus problem is a more big brain use of it as well imo

**Comment by ar492** [comment]
On second thought, I agree. The focus problem also has better test data.

**Pull request closed without merging**
