### PR TITLE
start import user data

### PR DESCRIPTION
**Pull request by bqi343**

### CODE REVIEW

**Comment by thecodingwizard** [comment]
In theory this should work? But would probably test this a lot since it overrides your data permanently ://

**Comment by bqi343** [comment]
> In theory this should work? But would probably test this a lot since it overrides your data permanently ://

if someone really wants to erase his data that's fine with me :)

**Comment by thecodingwizard** [comment]
I don't think class imports work. @jeffreymeng?

**Comment by jeffreymeng** [comment]
wdym by class imports

**Comment by thecodingwizard** [comment]
Export user data then import user data -- you lose the list of classes you're enrolled in I think

**Comment by jeffreymeng** [comment]
Where is user data exported?

Thanks,
Jeffrey Meng

--
Jeffrey Meng | jeffkmeng@gmail.com | jeffkmeng.com

**Comment by dongliu0426** [comment]
won't this let the user override the data (ex. daily streak)?

**Comment by thecodingwizard** [comment]
Yes, but they technically can already anyway. (Maybe we can add some
restrictions on streaks...)

**Comment by thecodingwizard** [comment]
hmm interesting I just tried again and user class import worked (and looking at the code it should work). This code seems fine but should probably be tested a bit more (?).

**Comment by thecodingwizard** [comment]
oops idk why so many files are changed, I'll move this to #706

**Pull request closed without merging**
