### PR TITLE
CSES Counting Paths Solution

### PR DESCRIPTION
**Pull request by dutinmeow**
I'm not sure if this problem is in any modules.

### CODE REVIEW

**Comment by maggie-j-liu** [comment]
I don't think it is... if it's not on the guide, why are you adding a solution? If you think it should be added, submit a problem suggestion!

**Comment by dutinmeow** [comment]
> I don't think it is... if it's not on the guide, why are you adding a solution? If you think it should be added, submit a problem suggestion!

**Comment by maggie-j-liu** [comment]
the problem suggestion got merged, but then removed in #1571 so i think this can be closed

**Comment by thecodingwizard** [comment]
fwiw Guide supports internal solutions for problems that appear in no modules (by adding to `extraProblems.json`). Still shows up in search engines

**Comment by maggie-j-liu** [comment]
oh, i didn't know that. is this something we want to actively support, and should we add it to the adding solutions module?

**Comment by thecodingwizard** [comment]
sure. I think extra internal solutions generally help:
- they boost site SEO
- they attract people who need help on that problem
- we might use that problem in the future

**Comment by bqi343** [comment]
@thecodingwizard so are we keeping this or not? personally, I think it should either be converted to a solution for a max flow since that problem is in the guide

**Comment by thecodingwizard** [comment]
I think we should keep this solution and add it to `extraProblems.json` for the benefits outlined above. I'm not 100% sure what you mean by "convert to a solution for max flow"...? it doesn't hurt to have solutions for more problems even if the problems are redundant right?

**Comment by bqi343** [comment]
I think changing one or two lines of this solution and adding file i/o solves max flow.

**Comment by bqi343** [comment]
@dolphingarlic what do you think?

**Comment by dolphingarlic** [comment]
@dutinmeow I agree that we should convert this solution to work for max flow (less work and I'd prefer USACO over CSES when a problem appears in both)

**Review by dolphingarlic — CHANGES_REQUESTED** [review]
.

**Comment by dutinmeow** [comment]
I have code written for both so it shouldn't take that long

**Comment by dutinmeow** [comment]
I'll close this PR and make a new one because the revisions are quite big

**Comment by dutinmeow** [comment]
The new PR is [here](https://github.com/cpinitiative/usaco-guide/pull/1903)

**Pull request closed without merging**
