### PR TITLE
usaco-767 C++ Implementation

### PR DESCRIPTION
**Pull request by envyaims**
_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

it is spring break and im bored

### CODE REVIEW

**Review by ryanchou-dev — APPROVED** [review]
envy orz

**Review by SansPapyrus683 — APPROVED** [review]

**Comment by envyaims** [comment]
any updates on this lol?

**Comment by ryanchou-dev** [comment]
umm, one more approval and we can merge

**Comment by envyaims** [comment]
pls

**Comment by SansPapyrus683** [comment]
@dongliu0426

**Review by dongliu0426 — APPROVED** [review]

**Pull request merged**
