### PR TITLE
Bin search fix

### PR DESCRIPTION
**Pull request by HarryWangATX**
Fixes python code in #833

### CODE REVIEW

**Comment by frodakcin** [comment]
Honestly I have no clue whether this is good python..

**Review by frodakcin — APPROVED** [review]
On a very surface level. I have no clue if it's actually good.

**Comment by HarryWangATX** [comment]
> Honestly I have no clue whether this is good python..

😭 @bqi343 do u know?

**Comment by frodakcin** [comment]
or we could have asked chez probably

**Comment by HarryWangATX** [comment]
@chezbgone ^

**Comment by chezbgone** [comment]
i didn't check the correctness of the algorithm, but this is much better python than before. It is almost always bad practice to use `exec` and `eval` in code unless you're trying to write code that intentionally changes itself (of something of a similar flavor).

**Review by chezbgone — APPROVED** [review]

**Comment by frodakcin** [comment]
Ok, thanks

**Pull request merged**
