### PR TITLE
Add resource to bitmask dp module

### PR DESCRIPTION
**Pull request by ar492**

### CODE REVIEW

**Review by darren-yao — APPROVED** [review]

**Comment by andrewwangva** [comment]
@darren-yao why merge? Idt the resource introduces anything new and isn't very thorough. Also note small changes like these don't warrant an author addition.

**Comment by ar492** [comment]
@andrewwangva the resource is the only one that gives a diagram to more clearly explain bitmask DP (maybe I should put this in the description of the resource). Regarding your second point, I am also not sure about the guidelines for being contributor vs author, but I added myself as contributor since I saw nwatx's blog as a resource and he is listed as contributor (not sure if he wrote any part of the module though).

**Comment by nwatx** [comment]
I wrote that specifically for the guide - cross compatible mdx and review process.

**Comment by ar492** [comment]
I'll make a new pr without myself as contributor then.

**Pull request merged**
