### PR TITLE
add difficulty to ProblemHit

### PR DESCRIPTION
**Pull request by aaronthechen**
adds difficulty mentioned in https://github.com/cpinitiative/usaco-guide/issues/86#issuecomment-788536196

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

### CODE REVIEW

**Comment by HarryWangATX** [comment]
image

**Comment by HarryWangATX** [comment]
also i think the font color shouldn't be gray in the tag box thing

**Comment by aaronthechen** [comment]
> did u test this?

sorry this is my first pr, how would i go about running tests?

**Comment by aaronthechen** [comment]
> image

I think this was already in the problems page, I didn't modify the selection list

**Review by bqi343 — APPROVED** [review]
Screen Shot 2023-01-05 at 10 56 46 AM

Looks good. Though maybe the color of "Very Easy" should be changed, since it's the same color as the tags.

**Pull request merged**
