### PR TITLE
Complete Recursion Quiz

### PR DESCRIPTION
**Pull request by dutinmeow**
From [here](https://github.com/cpinitiative/usaco-guide/pull/2162)

### CODE REVIEW

**Review by SansPapyrus683 — APPROVED** [review]
i thought i approved this
but idk

**Review by ryanchou-dev — APPROVED** [review]
yeah cool, yk you can reopen a pr right?

**Comment by dutinmeow** [comment]
> yeah cool, yk you can reopen a pr right?

Wait how?

**Comment by ryanchou-dev** [comment]
> > yeah cool, yk you can reopen a pr right?
> 
> Wait how?

image

**Review by dongliu0426 — APPROVED** [review]

**Pull request merged**
