### PR TITLE
update PIE.mdx

### PR DESCRIPTION
**Pull request by freakin23**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

The previous value of `VALMAX`  was too high thus resulting in TLE, therefore I changed it accordingly.

### CODE REVIEW

**Comment by freakin23** [comment]
I realized that there was a good chance that the 20th value would cause some trouble with the page width, so I changed it back. Just changing the number is enough.

**Review by ryanchou-dev — APPROVED** [review]
👍 thank you for catching these!

**Comment by ryanchou-dev** [comment]
> I realized that there was a good chance that the 20th value would cause some trouble with the page width, so I changed it back. Just changing the number is enough.

I don't think it makes too much of a difference, the table & latex will overflow nonetheless.

**Comment by freakin23** [comment]
> 👍 thank you for catching these!

Ur welcome 🤗

**Review by SansPapyrus683 — APPROVED** [review]
mihnea strikes again

**Pull request merged**
