### PR TITLE
put new solutions in the proper folder

### PR DESCRIPTION
**Pull request by danielzsh**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by danielzsh** [comment]
@envyaims this should fix the folder issue for new solutions, would you mind testing it rq once it deploys 🙏🏻

**Comment by envyaims** [comment]
for new internal solutions, can you make it also go into contents and change kind from whatever it is to "internal" or is that too much D;

**Comment by danielzsh** [comment]
Isn't this already a feature? When I open `cf-468B`, the editor automatically opens `content/4_Gold/DSU.mdx` and updates metadata to internal:
image
Or are you talking about something else?

**Comment by envyaims** [comment]
if you tested it works then it's probably fine then

**Comment by danielzsh** [comment]
okok would you mind giving an approval bc its needed to merge now 😭

**Review by envyaims — APPROVED** [review]

**Pull request merged**
