### PR TITLE
remove the last 2 language specific modules

### PR DESCRIPTION
**Pull request by SansPapyrus683**
_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [ ] I have tested my code
- [x] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [x] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

legit don't know if this works

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
LET'S GOOOOO

**Comment by TruaShamu** [comment]
This is the one you want me to review? It looks good to me.

**Review by TruaShamu — APPROVED** [review]

**Comment by bqi343** [comment]
Why? Some modules (ex. [this one](https://usaco.guide/silver/binary-search?lang=cpp)) use lambdas and I've ran into the problems mentioned in the second module more than once, so it's worth nothing *somewhere*.

**Comment by SansPapyrus683** [comment]
i mean if you want i think they should be just included in the "writing generic code" section- lambdas don't deserve to have a module all to theirselves

**Comment by nwatx** [comment]
seems like writing generic code is long enough, so the distinction is reasonable

**Review by bqi343 — CHANGES_REQUESTED** [review]
disapprove

> i mean if you want i think they should be just included in the "writing generic code" section- lambdas don't deserve to have a module all to themselves

you can move them if you want, but don't just delete them :/

**Pull request closed without merging**
