### PR TITLE
Add lang query param for table of content links

### PR DESCRIPTION
**Pull request by nathangong**
This should address #2060, let me know if there are any issues

### CODE REVIEW

**Comment by maggie-j-liu** [comment]
seems fine, but i noticed another problem (idk might be related) where if you're on a certain module and you click on the module name again, the lang param also disappears
so if i'm on the two pointers module and i click two pointers again, the lang disappears
image

**Comment by nathangong** [comment]
hm interesting

**Comment by nathangong** [comment]
Should I just add the language parameter for the side nav links?

**Comment by nathangong** [comment]
Rip this PR also causes some unintended behaviors (copying-pasting the TOC link will include the language param), so not sure if it's worth it or not

**Comment by nathangong** [comment]
Closing this for now -- I think there probably exists a better solution that can solve both problems at once

**Pull request closed without merging**
