### PR TITLE
Problem Suggestion: Add "Perimeter" to Silver - More Operations on Ordered Sets

### PR DESCRIPTION
**Pull request by jeffkmeng**
User `M6y0nf7NEpbM1BhgQ8ZvYXylFg12` suggested adding the problem [Perimeter](http://www.usaco.org/index.php?page=viewproblem2&cpid=244) to the `general` table of the module [Silver - More Operations on Ordered Sets](https://usaco.guide/silver/intro-ordered#problemlist-general).

**Automatically Generated JSON:**
```json
{
  "uniqueId": "usaco-244",
  "name": "Perimeter",
  "url": "http://www.usaco.org/index.php?page=viewproblem2&cpid=244",
  "source": "Old Silver",
  "difficulty": "Normal",
  "isStarred": false,
  "tags": [
    "Set",
    "Simulation"
  ],
  "solutionMetadata": {
    "kind": "USACO",
    "usacoId": 244
  }
}
```
**Additional Notes**: None

*This PR was automatically generated from a user-submitted problem suggestion on the USACO guide.*

### CODE REVIEW

**Comment by thecodingwizard** [comment]
@jeffreymeng ?

**Comment by jeffreymeng** [comment]
@thecodingwizard huh?

**Comment by maggie-j-liu** [comment]
@jeffreymeng 
> why is the usacoId a number again??? it was working before...

**Comment by jeffreymeng** [comment]
Hmm that’s weird. I just redeployed so hopefully it’ll be fixed in the future.



--
Jeffrey Meng ***@***.*** | jeffkmeng.com

**Pull request closed without merging**
