### PR TITLE
Hint for Moocast

### PR DESCRIPTION
**Pull request by brad182**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Review by SansPapyrus683 — APPROVED** [review]
i guess

**Comment by envyaims** [comment]
for hint 2 didnt you just restate the problem?

**Comment by SansPapyrus683** [comment]
if you can come up w/ a better one i'll replace it

**Review by ryanchou-dev — APPROVED** [review]
perfect :D

**Comment by ryanchou-dev** [comment]
> for hint 2 didnt you just restate the problem?

oops didn't see this, lmk if u have a better one and ill change it 
image

**Pull request merged**
