### PR TITLE
erm please work

### PR DESCRIPTION
**Pull request by envyaims**
_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
image

**Comment by dustin-miao** [comment]
Is there a reason you're adding an internal editorial if you're just going to give the exact same solution?

**Comment by SansPapyrus683** [comment]
think we ok'd redundant editorials a long time ago
allows for python/java solutions

**Comment by envyaims** [comment]
> Is there a reason you're adding an internal editorial if you're just going to give the exact same solution?
 
the official editorial doesn't even have implementation lol?

**Review by SansPapyrus683 — APPROVED** [review]
i'll trust me in the past

**Pull request merged**
