### PR TITLE
Update Func_Graphs.problems.json

### PR DESCRIPTION
**Pull request by TheScarletPhoenix**
added a "hard" problem

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [X] I have tested my code.
- [X] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [X] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [X] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by TheScarletPhoenix** [comment]
Closes #4556

**Comment by SansPapyrus683** [comment]
you suggested this didn't you lol

**Comment by envyaims** [comment]
why is this functional graph?

**Comment by TheScarletPhoenix** [comment]
who me? no. i don't even know how to.

**Comment by TheScarletPhoenix** [comment]
it's not directly a functional graph, but it's related. it's the approach used to solve the problem.

**Comment by TheScarletPhoenix** [comment]
any update?

**Comment by SansPapyrus683** [comment]
waiting for envy to give his verdict

**Comment by TheScarletPhoenix** [comment]
@envyaims waiting for ur verdict

**Comment by envyaims** [comment]
change to very hard and its fine

**Comment by TheScarletPhoenix** [comment]
done

**Comment by bqi343** [comment]
@TheScarletPhoenix can you please link the issue by adding "Closes #4556" to your first post?

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by TheScarletPhoenix** [comment]
done

**Pull request merged**
