### PR TITLE
Fix for issue #2226 - Home Page dark theme and light theme

### PR DESCRIPTION
**Pull request by omkarbajaj073**
- Changed background and text colors for dark and light themes, with some other small changes.
- Also, a small change to the color scheme of the progress bar on the dashboard. Looks better imo, but not that big of a change. If this change is discarded, the sample progress bar on the home page should also be changed for consistency (although this is not strictly necessary)

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ DONE ] I have tested my code.
- [ DONE ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ DONE ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

### CODE REVIEW

**Comment by omkarbajaj073** [comment]
So what do I do about that lmao? Do I change it or not, and if so, anything I shud keep in mind?

**Comment by ryanchou-dev** [comment]
umm, let's see if anybody has any other opinions?

cc: @jjliewie @RedBlueBird  @maggie-j-liu @TruaShamu

**Comment by maggie-j-liu** [comment]
image
image

some parts of the homepage look a bit weird on dark mode... will take a look at the rest later

**Comment by RedBlueBird** [comment]
> umm, let's see if anybody has any other opinions?
> 
> cc: @jjliewie @RedBlueBird @maggie-j-liu @TruaShamu

I think the design looks fine,
though if I have to add something, the gradient text `curated, high-quality resources` provides less contrast with the white background in modes not dark mode.

**Comment by omkarbajaj073** [comment]
> image image
> 
> some parts of the homepage look a bit weird on dark mode... will take a look at the rest later

Fixed this. The glow for the title is back to what it was earlier and I've removed the background animation for the feature elements. I'll commit if others want this too.

**Comment by omkarbajaj073** [comment]
Changed the gradient too - it looks much better.
image

**Comment by thecodingwizard** [comment]
hmmm idk how much I like the gray background on light mode... We could try a really really light shade of gray? Or even just not have a background possibly

**Comment by thecodingwizard** [comment]
also it's fine if certain sections are dark on a light theme. We could also just not change anything for light theme, but make everything dark for dark theme

**Comment by omkarbajaj073** [comment]
I can make it a lighter shade of gray, but I didn't like it when certain parts of the page were dark on the light theme. It doesn't fit with the rest of the site, plus it doesn't really address the issue itself.

**Comment by omkarbajaj073** [comment]
> beautiful tell me when you're 100% done & i'll merge

Done. But there's still some disagreement, so wait on the merge ig.

**Comment by thecodingwizard** [comment]
Hmm, I think mostly I just don't really like how the current dark gray looks on light theme. I think one of the following might be better:

1. Keep light mode the same, make everything dark in dark mode
2. Get rid of light mode entirely. Make everything in the homepage dark, even in light mode. Have light mode for the rest of the website
3. Replace dark backgrounds with light gray backgrounds (similar to epicreact.dev, or kentcdodds.com in light mode?) (I think this should work but I'll have to see it...)
4. Get rid of dark backgrounds and replace with white backgrounds in light mode (I think this should work but I'll have to see it...)

I'm also fine keeping the status quo in light mode, merge the changes for dark mode, and then continue discussing what it should look like in light mode later if you want to get some of your changes on the site now :)

Some minor notes I have about dark mode:

- "Learn USACO. Efficiently." I feel like the title text is a little too bright -- would it be better as `text-gray-50` or something?
- The highlight color for "Efficiently" should probably be dark
- The resources / problem table header should probably be dark. Also I don't think there should be a box shadow in dark mode?
- The "View Forum" link under help when you need it seems a little too dark (?)
- It would be nice (but not critical) to have the image for the usaco forum change to dark in dark mode. we can probably push this one off to later if you don't want to deal with it right now though
- In the "Created by the CP Initiative" section, the borders probably shouldn't be so light? Alternatively, we can get rid of the border in dark mode and just make the background color of each card one shade lighter than the background. Also, I think the "Learn More" buttons are also a little too dark (?)

Thanks again for making this PR! Dark mode not being completely dark is an issue that would be nice to fix :D

**Comment by omkarbajaj073** [comment]
Fixed all the points in the dark theme. For the final point, I have commented out the existing style and added a new one with no border. We can keep whichever looks better. 
For the light theme, I made the gray bg much lighter. I feel like the home page shouldn't be dark on the light theme since the rest of the site is light. If the rest of the site were dark too, it wud hv been fine. Then again, I can remove it if that's that's the consensus here. Also, the sponsor logos don't fit well with in the light theme. I'll be looking to change that next.

**Comment by maggie-j-liu** [comment]
i think the lighter gray looks better :)

dark mode looks okay (didn't look at the details yet) but a few notes about light mode:
positioning of text is different from dark mode
image

i think these lines are too dark
image
image

**Comment by omkarbajaj073** [comment]
> i think these lines are too dark

How's this? I made everything 100-200 points lighter.
image
image

**Comment by ryanchou-dev** [comment]
looks great!

maybe a little more spacing in between the tag and name here:
image

fix the spacing for the headers:
image

and make some of the text here a darker shade of grey

image

**Comment by omkarbajaj073** [comment]
Done. I've also made the text on the XCamp logo black on the light theme. For easy and fun coding, you'll have to design a separate image.

**Comment by omkarbajaj073** [comment]
Anything else u guys want me to do to the home page? Or any other pages that need style changes other than the home page?

**Comment by omkarbajaj073** [comment]
Any problem with the styles? Am I missing anything?

**Comment by maggie-j-liu** [comment]
oops change is pretty major so we should probably wait for @thecodingwizard to review...

**Comment by omkarbajaj073** [comment]
Cool. Take your time. If there r any other changes u guys want me to make, just lmk.

**Comment by omkarbajaj073** [comment]
Cool. Take your time. If there r any other changes u guys want me to make, just lmk.

**Comment by thecodingwizard** [comment]
oops sorry, I've been kinda busy this week D:

- In light mode perhaps we should get rid of the glow effect? I don't think it works that well...
- For the "Created by CP Initiative" cards, what if we made the background white, with a really light border `gray-50`, or `gray-100` perhaps? right now it feels a little weird since the section right above it has a gray background
- In the "Join our team" vs "help us financially" section, the background feels a little darker than the other ones? Also I think the divider should be a lot lighter (`gray-700` or less?)
- The "donate via paypal" and "sponsorship prospectus" link color should probably be a little darker?
- Sponsor photos look kinda weird in light mode but there's not much we can do to fix it so it's probably fine
- In the authors you can trust section, the borders should probably be a lot lighter? `50` or `100`? idk whatever looks good
- Also, the blurb might look better if it was just `text-gray-800`? (same with the title, maybe `text-gray-700` or also `text-gray-800`)?

Dark mode looks good. Thanks again!

**Comment by omkarbajaj073** [comment]
>     * In the "Created by the CP Initiative" section, the borders probably shouldn't be so light? Alternatively, we can get rid of the border in dark mode and just make the background color of each card one shade lighter than the background. Also, I think the "Learn More" buttons are also a little too dark (?)

For the 2nd point, u sent this earlier. Honestly, I thought it was a big improvement. I can change it back though if u want.
Here's what it looks like with the border - 
image

**Comment by omkarbajaj073** [comment]
For the 3rd point, that is by design as the logo of EasyFunCoding is not readable on a lighter bg. That logo is directly taken from the image assets, so we'll need someone to design a logo with "Easy" and "Coding" in black text. This will resolve the 5th point too.

For the author's section, is this what you're going for - 
image

**Comment by omkarbajaj073** [comment]
For the glow effects, this is how it looks (after adding a border to the button) - 
image

This in my opinion looks better - removing the glow of the title only - 
image

Lmk which to keep.

**Comment by omkarbajaj073** [comment]
Here's another screenshot - 
(removing title glow)
image

(removing button glow too)
image

**Comment by thecodingwizard** [comment]
> For the 2nd point, u sent this earlier. Honestly, I thought it was a big improvement. I can change it back though if u want.
Here's what it looks like with the border -

- I think the screenshot you sent is fine? I think my comment was more in reference to the dark mode border being too light, but I don't remember exactly :P


Also for the authors section, what's wrong with the current blue background for light mode? https://usaco.guide/


> This in my opinion looks better - removing the glow of the title only -

Agreed. I think remove glow from title but keep glow for button is fine

**Comment by omkarbajaj073** [comment]
Cool. 
Abt the background of the author section, the dark blue looked ok when part of the light theme was black, but now that everything is white or light grey, the dark blue wouldn't fit.

**Comment by thecodingwizard** [comment]
I feel like it might still work? Ex: https://usaco-guide-dvfvclpb5.vercel.app/

Or if we really don't like it then there's also no need to make it light blue -- we could just make it a light gray background (or no background)? I feel like the light blue there is sort of awkward especially with the border...

**Comment by omkarbajaj073** [comment]
Alright. For the CPI Card, keeping the border and removing the bg. Changed the glow too. 
I still don't like the dark blue bg, but if everyone else likes it, I can make that change. I also tried a few things with the bg and the author's title - 

image

image

**Comment by omkarbajaj073** [comment]
@thecodingwizard our options r the above 2 images, the dark blue on the site rn and the light blue of the initial PR. Which shud I keep?

**Comment by thecodingwizard** [comment]
I'm fine with either. Actually, I think light blue label, but gray icons might be best? up to you

**Comment by omkarbajaj073** [comment]
Blue label, gray icons - here's how it looks - 
image

I feel like this is the best. 
R these the final changes?

**Comment by omkarbajaj073** [comment]
I've pushed the new changes. Lmk is there's anything else left.

**Comment by thecodingwizard** [comment]
@omkarbajaj073 I made some minor UI changes for the index page: https://github.com/cpinitiative/usaco-guide/pull/2779/commits/8a4b7083a6794e9709c6c8707fe0115ba2cb10cf

Do these look good to you?

**Comment by omkarbajaj073** [comment]
tbh most of them are hardly noticeable to me. just one thing - I'd stick with the border-gray-200 for the CPI Cards, but doesn't rly matter much. Otherwise, ig we're done

**Comment by SansPapyrus683** [comment]
image
image

**Comment by thecodingwizard** [comment]
> tbh most of them are hardly noticeable to me. just one thing - I'd stick with the border-gray-200 for the CPI Cards, but doesn't rly matter much. Otherwise, ig we're done

I updated `border-gray-100` to `border-gray-200` but changed border width to 1px since I felt 2px width + border gray 200 was too dark. but if other people disagree I'm open to changing it.

---

Thanks for all the work you put into this PR!

**Pull request merged**
