### PR TITLE
Add an RURQ resource

### PR DESCRIPTION
**Pull request by rainy789**
_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
why's it called "second thread"

**Comment by rainy789** [comment]
> why's it called "second thread"

updated

**Comment by SansPapyrus683** [comment]
could you mind summarizing what this resource contributes that the others don't?

**Comment by rainy789** [comment]
> could you mind summarizing what this resource contributes that the others don't?

I found this one helpful for learning about lazy segtree because it's in video format and it gives an introduction to segment tree and lazy propagation for _range update and range query_. It also provides a walkthrough of a related problem. 

The CF edu one (the first one in the list) contains a video tutorial but it only covers _range update and point query_. The other resources are in text format.

**Comment by SansPapyrus683** [comment]
> The CF edu one (the first one in the list) contains a video tutorial but it only covers _range update and point query_

?
image
step 2 right here covers it, no?

**Comment by rainy789** [comment]
Oh I didn't do part 2. Closing the PR.

**Pull request closed without merging**
