### PR TITLE
move rectangle geometry to additional category

### PR DESCRIPTION
**Pull request by thecodingwizard**
I don't think rectangle geometry belongs under "fundamentals," but if other people feel otherwise please feel free to say so :O

### CODE REVIEW

**Review by HarryWangATX — APPROVED** [review]

**Comment by HarryWangATX** [comment]
yea i do feel like rectgeo ahouldnt be in fundamentals at least from the things on fundamentals. im fine with this tho

**Comment by bqi343** [comment]
I still think rect geo should be the second module people do.

**Comment by frodakcin** [comment]
Surely it must come before ad-hoc

**Comment by thecodingwizard** [comment]
okay sure (ig rect geo problems are good intro problems anyway)

**Pull request closed without merging**
