### PR TITLE
Update USACO open19-500.mdx

### PR DESCRIPTION
**Pull request by Aryansh-S**
Added a concrete solution for the math approach.

### CODE REVIEW

**Comment by bqi343** [comment]
You should mention Kruskal's somewhere.

**Comment by Aryansh-S** [comment]
> You should mention Kruskal's somewhere.

It's already mentioned in your solution.

**Comment by bqi343** [comment]
Yeah, but this solution is essentially just performing Kruskal's algorithm as well.

**Comment by Aryansh-S** [comment]
> Yeah, but this solution is essentially just performing Kruskal's algorithm as well.

Good point, added to the end

**Pull request merged**
