### PR TITLE
fix katex warnings

### LINKED ISSUE #3307: LaTeX Build Warnings
When running `yarn develop`:

> warn LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]

How to determine which file is resulting in this warning?

### PR DESCRIPTION
**Pull request by bqi343**
closes #3307

I just looked through all the occurrences of `\\` and `\newline` ... 

is there a better way (e.g., get gatsby to print locations of warnings)? @thecodingwizard 

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

### CODE REVIEW

**Comment by thecodingwizard** [comment]
I don't know; I think this is fine as-is (since editors presumably will get latex errors as they're editing a file anyway?). If we really wanted to, I think https://github.com/cpinitiative/usaco-guide/blob/master/src/mdx-plugins/rehype-math.js#L47 we could modify something here to print a line number but I'm not sure.

**Comment by thecodingwizard** [comment]
could this be because gatsby caches the resuts of compiling files? ie. if you change and save the file, that would force gatsby to recompile (which you can test by adding a console.log to verify katex is actually running) and see if it outputs an error?

**Comment by thecodingwizard** [comment]
also what do you mean by "an error is never thrown"? In the rehype-math file I linked it seems like we are setting `throwOnError` to fale

**Comment by bqi343** [comment]
I mean that the code in the `catch` block never runs, because an error is never thrown in `try`. btw I just noticed that https://katex.org/docs/options.html allows you to pass a function in place of `strict`, will see if that works

**Comment by bqi343** [comment]
huh for some reason they made it so that it's impossible to throw an error even if you pass a custom handler ...

https://github.com/KaTeX/KaTeX/blob/b58a43212e4178ed46cf8e42d67e88b9c8df9c24/src/Settings.js#L300

**Pull request merged**
