### PR TITLE
Set "Checksum" difficulty to "Hard"

### PR DESCRIPTION
**Pull request by SimonBerens**
No way this is an easy...

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [X] I have tested my code
- [X] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [X] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

### CODE REVIEW

**Comment by SimonBerens** [comment]
tbh maybe "very hard" would be better... I hope I'm not exposing myself here :P

**Comment by SansPapyrus683** [comment]
lol ye i agree with you

**Comment by SimonBerens** [comment]
> lol ye i agree with you

as in I should change it to very hard?

**Comment by SansPapyrus683** [comment]
uh i think hard would be more appropriate

**Comment by SimonBerens** [comment]
> uh i think hard would be more appropriate

ok sweet, so do I need to do anything else to get this merged?

**Comment by SansPapyrus683** [comment]
idk lemme ask some other ppl

**Comment by SansPapyrus683** [comment]
@maggie-j-liu @nathangong @dutinmeow 
what do yall think

**Comment by dutinmeow** [comment]
doesn't seem that hard, probably "normal" at most

**Comment by nathangong** [comment]
Normal seems fitting, could also be hard

**Comment by SansPapyrus683** [comment]
bruh
alr we're changing this to hard
word of the mod is final

**Comment by dutinmeow** [comment]
wait what
this is blatant mod abuse

**Comment by dutinmeow** [comment]
this literally has 0 approves

**Comment by dutinmeow** [comment]
still mod abuse

**Pull request merged**
