### PR TITLE
USACO problem tables

### PR DESCRIPTION
**Pull request by bqi343**
See `/general/usaco-bronze`.

Todo:
 - Allow solution / tags / difficulty (?) for USACO problems to be added without problem having to be part of a module.
   - Ex. sprinklers platinum may be an application of prefix sums, but maybe we don't actually want it to appear in the silver prefix sums module since it's too hard ...
 - Headers for seasons (ex. 2019-20) should appear as normal markdown headers (##)

### CODE REVIEW

**Comment by thecodingwizard** [comment]
> Allow solution / tags / difficulty (?) for USACO problems to be added without problem having to be part of a module.

Is this referring to the problem search?

**Comment by bqi343** [comment]
I was referring to the tables I added :P

**Comment by thecodingwizard** [comment]
ah I see. Would problems with a module associated with them inherit difficulty / tags & stuff from the module?

**Comment by bqi343** [comment]
> ah I see. Would problems with a module associated with them inherit difficulty / tags & stuff from the module?

Yeah.

**Comment by thecodingwizard** [comment]
hmm, why not make the problems w/ no associated modules part of the Bronze/Silver/Gold/Plat modules? :O (export the problems without using them anywhere)

**Review by thecodingwizard — APPROVED** [review]

**Comment by bqi343** [comment]
Copied over some parts from `MarkCompleteButton` and `ProblemStatusCheckbox`, maybe messed up some of the CSS

**Comment by thecodingwizard** [comment]
image

The title 2016-2017 is no longer needed right?

**Review by thecodingwizard — APPROVED** [review]

**Pull request merged**
