### PR TITLE
Split solutions into solution folders

### LINKED ISSUE #3316: Split solutions by division
Have a separate folder for each division's solutions so that the appropriate codeowners get notified when a solution is modified. If a problem is in multiple divisions, the corresponding solution can go in the folder corresponding to any of those divisions.

### PR DESCRIPTION
**Pull request by mjh316**
_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

Splits /solutions/ into divisions. There was a merge conflict from some update to the files today, so hopefully we can resolve that as well. Closes #3316

### CODE REVIEW

**Comment by HarryWangATX** [comment]
can u edit the CODEOWNERS file too

**Comment by SansPapyrus683** [comment]
oh no, conflicts

**Review by bqi343 — APPROVED** [review]

**Comment by bqi343** [comment]
@mjh316 planning any other changes? can merge if no

**Comment by mjh316** [comment]
@bqi343 Not to this PR, so merging is a go. I plan on working on some other issues, so if something comes up, I'll just open another PR.

**Pull request merged**
