### PR TITLE
Update userLang.ts

### PR DESCRIPTION
**Pull request by bqi343**
addresses https://github.com/cpinitiative/usaco-guide/issues/1550#issuecomment-846425681 ?

Intended behavior:
 1. Suppose that current language is C++.
 2. Visit `/gold/bfs?lang=java`, sets your language to Java.
 3. Visit settings page, should see that your language is set to Java.
 4. Change your language in the settings page (say, back to C++).
 5. Press the back button (going back to `/gold/bfs`). Module should now switch to C++.

### CODE REVIEW

**Comment by maggie-j-liu** [comment]
> 5. Press the back button (going back to /gold/bfs). Module should now switch to C++.

The module switches to c++, but the url is still java

**Comment by bqi343** [comment]
oops looks like it only changes when you're signed in >,<

**Comment by bqi343** [comment]
@maggie-j-liu lmk if it's alright now

**Comment by maggie-j-liu** [comment]
Yep, it works now

**Review by maggie-j-liu — APPROVED** [review]

**Pull request merged**
