### PR TITLE
try using node 20

### PR DESCRIPTION
**Pull request by danielzsh**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
love how deployment works even with failed tests

**Comment by danielzsh** [comment]
@SansPapyrus683 would u mind approving so we can get this merged

**Review by SansPapyrus683 — APPROVED** [review]
ok cool, but like why the need for upgrading + what did u have to fix

**Comment by danielzsh** [comment]
it was a dependabot thing

**Pull request merged**
