### PR TITLE
added new content authors

### PR DESCRIPTION
**Pull request by HarryWangATX**
_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

### CODE REVIEW

**Comment by HarryWangATX** [comment]
@ChuangSheep @Keys9873 @EulerPascal404 @envyaims @876pol is this good?

**Comment by HarryWangATX** [comment]
also accept the team invites in your inbox :)

**Review by ChuangSheep — APPROVED** [review]
nice, thanks! ❤️

**Comment by EulerPascal404** [comment]
> @ChuangSheep @Keys9873 @EulerPascal404 @envyaims @876pol is this good?

I changed the date I joined. I am pretty sure it was June, but it looks good otherwise.

**Review by 876pol — APPROVED** [review]
looks great!

**Comment by HarryWangATX** [comment]
added you guys to the readme btw.

**Review by envyaims — APPROVED** [review]
uwu

**Pull request merged**
