### PR TITLE
Move BFS to Silver

### PR DESCRIPTION
**Pull request by ryanchou-dev**
super sorry if some of the stuff is wrong, i spent like 3 hours fixing redirects and deployments TwT

---
_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

### CODE REVIEW

**Comment by ryanchou-dev** [comment]
Fixes #3544

**Review by bqi343 — APPROVED** [review]
a lot of stuff in Graph Traversal needs to be added or cleaned up, but ok for now

**Comment by SansPapyrus683** [comment]
> a lot of stuff in Graph Traversal needs to be added or cleaned up

elaborate?

**Comment by bqi343** [comment]
check the incompletesections. also, there's a lot of commented-out code for some reason.

**Review by envyaims — APPROVED** [review]
if this works then sure

**Comment by Aadit-Ambadkar** [comment]
#1843 🤔 took 2 years

**Pull request merged**
