### PR TITLE
quick fixes - balanced photos

### PR DESCRIPTION
**Pull request by dongliu0426**
suggestions from #671

### CODE REVIEW

**Comment by frodakcin** [comment]
I've made some more changed. What you changed was fine.

**Comment by frodakcin** [comment]
I dropped the connection between random access making distance O(N), should probably change wording to add that back

**Review by darren-yao — APPROVED** [review]
where's the c++ code/?

**Comment by dongliu0426** [comment]
> where's the c++ code/?

its under the explanation

**Comment by frodakcin** [comment]
I changed phrasing to

"We may **not** use [`std::set`](http://www.cplusplus.com/reference/set/set/) because it does not support indexing. Additionally, since BBSTs do *not* support random access, using operations such as [`std::distance`](http://www.cplusplus.com/reference/iterator/distance/) to index takes linear time."

Is this accurate @bqi343 ?

**Comment by bqi343** [comment]
sure

**Comment by frodakcin** [comment]
ok thanks

**Comment by frodakcin** [comment]
@dongliu0426 are you ok with the changes here?

**Comment by dongliu0426** [comment]
> @dongliu0426 are you ok with the changes here?

yeah

**Comment by frodakcin** [comment]
I'll just merge it

**Review by frodakcin — APPROVED** [review]

**Pull request merged**
