### PR TITLE
Update ProblemHits title to be clickable

### LINKED ISSUE #1646: UI: problem search results not clickable
Small inconvenience that probably has gone unnoticed by common users of the webapp: when I perform a search on https://usaco.guide/problems/, the search results come in boxes, of which neither the box itself nor the title of the box are clickable. This was particularly confusing for me since I didn't realize there was anything clickable in the box for a while, since the links have gone so far as to be greyed out.

I'm thinking that the they should both link to the problem, but feel free to bring up other ideas.

### PR DESCRIPTION
**Pull request by nwatx**
Resolves #1646

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
image
So right now clicking the white text leads you straight to the problem statement- I think it'd be cool if it redirects to the USACO Guide URL instead.

**Comment by maggie-j-liu** [comment]
> Some problems appear on the guide multiple times

which url do you suggest it directs to? just the first?

**Comment by maggie-j-liu** [comment]
can the entire box be made clickable or are stacked links too complicated?

**Comment by nwatx** [comment]
> can the entire box be made clickable or are stacked links too complicated?

it can, though then that would remove the purpose of the below URLs i think. @thecodingwizard opinion?

**Comment by thecodingwizard** [comment]
err I think the entire box being clickable might be a bit weird.

Also, there is a planned rewrite of the Problems page (but who knows when that will happen!)

**Comment by nwatx** [comment]
> image
> So right now clicking the white text leads you straight to the problem statement- I think it'd be cool if it redirects to the USACO Guide URL instead.

do you mean the solution page?

**Comment by SansPapyrus683** [comment]
No, I mean a URL like [this](https://usaco.guide/gold/knapsack#problem-cses-1665).

**Comment by maggie-j-liu** [comment]
> No, I mean a URL like [this](https://usaco.guide/gold/knapsack#problem-cses-1665).

The problem with that is that one problem might appear in multiple modules, and thus have multiple urls.

**Comment by bqi343** [comment]
> So right now clicking the white text leads you straight to the problem statement- I think it'd be cool if it redirects to the USACO Guide URL instead.

Can't you just click on "String Searching" if you want the guide URL?

**Comment by nwatx** [comment]
@thecodingwizard I suppose a temporary fix wouldn't hurt. But feel free to close this issue otherwise.

**Review by HarryWangATX — APPROVED** [review]

**Comment by thecodingwizard** [comment]
I guess it doesn't hurt...

**Pull request merged**
