### PR TITLE
spruce up intro ds mod

### PR DESCRIPTION
**Pull request by SansPapyrus683**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by TheGamingMousse** [comment]
idt the part about iterating a vector with iterators is very necessary, as i doubt anyone would realistically do that. maybe including that to intro to set/map tho, altho it's still a bit niche

**Comment by SansPapyrus683** [comment]
no yeah i'm just a bit nervous about removing anything in general lol
if enough people agree i'll do it

**Review by ryanchou-dev — APPROVED** [review]

**Comment by ryanchou-dev** [comment]
> idt the part about iterating a vector with iterators is very necessary, as i doubt anyone would realistically do that. maybe including that to intro to set/map tho, altho it's still a bit niche

really? i do it pretty commonly 👀

**Comment by ryanchou-dev** [comment]
we can discuss removals/other content in another pr/chat

**Pull request merged**
