### PR TITLE
Redid Garland Sol (And Fixed Rect Geo Sol)

### PR DESCRIPTION
**Pull request by SansPapyrus683**
you know how i work

### CODE REVIEW

**Comment by ryanchou-dev** [comment]
wait why is the problem names garland but the solution page is:
image

**Comment by SansPapyrus683** [comment]
uh that's way
way too long

**Review by jessechoe10 — APPROVED** [review]

**Comment by SansPapyrus683** [comment]
sorry for not splitting it, idk how to do branches and stuff like that

**Comment by ryanchou-dev** [comment]
> wait why is the problem named garland but the solution page is:
> image

wait is this fine then?

**Review by ryanchou-dev — APPROVED** [review]
code looks good

**Review by dongliu0426 — APPROVED** [review]

**Pull request merged**
