### PR TITLE
Add cleaner solution

### PR DESCRIPTION
**Pull request by danielzsh**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by danielzsh** [comment]
can I rename `pref_sum` to `query` in BIT 🙏

**Comment by SansPapyrus683** [comment]
why

**Comment by danielzsh** [comment]
I feel like query is the much more standard name for the function this is
my first time seeing "pref_sum" (the latter also just looks uglier honestly)

**Comment by SansPapyrus683** [comment]
i mean "query" gives no info about the actual functionality
it's the more standard name because 99% of cp code is not written for other people to read- it's to get ac
usaco guide code, on the other hand, is written to be readable (or at least i think that should be the case)

**Comment by danielzsh** [comment]
btw, any reason the bit template is 0-indexed? most bits ive seen are 1-indexed as well

**Comment by danielzsh** [comment]
image

proof of ac [here](https://judge.yosupo.jp/submission/194360)

**Comment by SansPapyrus683** [comment]
> btw, any reason the bit template is 0-indexed? most bits ive seen are 1-indexed as well

given that most things in cs are 0-indexed, i believe our bit should be that way
idk makes it more intuitive for me since i don't have to +1 or whatever

**Review by SansPapyrus683 — APPROVED** [review]
won't get too picky on this one since it's already a massive improvement over benq

**Comment by danielzsh** [comment]
lmfao those 200 line template solutions need to be phased out

**Comment by danielzsh** [comment]
(btw do you have any idea what sweepline mo's is)

**Comment by SansPapyrus683** [comment]
hell if i know

**Pull request merged**
