### PR TITLE
Create CF Santa's Bot.mdx

### PR DESCRIPTION
**Pull request by jeffarjeffar**
Created solution for problem 1279D (Santa's bot)

### CODE REVIEW

**Comment by bqi343** [comment]
You need to link the solution in the module as described [here](https://usaco.guide/general/contributing#adding-a-solution) (though isn't there an editorial already?)

Also, prefix the id with `cf` rather than `codeforces` (like the other solutions).

**Comment by jeffarjeffar** [comment]
> You need to link the solution in the module as described [here](https://usaco.guide/general/contributing#adding-a-solution) (though isn't there an editorial already?)
> 
> Also, prefix the id with `cf` rather than `codeforces` (like the other solutions).

Yeah, there is a codeforces editorial, but no internal sol.
Is an internal solution preferred?

**Comment by bqi343** [comment]
> > You need to link the solution in the module as described [here](https://usaco.guide/general/contributing#adding-a-solution) (though isn't there an editorial already?)
> > Also, prefix the id with `cf` rather than `codeforces` (like the other solutions).
> 
> Yeah, there is a codeforces editorial, but no internal sol.
> Is an internal solution preferred?

No, if the CF editorial is already okay (though it looks like it has some typos).

**Review by thecodingwizard — CHANGES_REQUESTED** [review]
> You need to link the solution in the module as described here (though isn't there an editorial already?)
> 
> Also, prefix the id with cf rather than codeforces (like the other solutions).

**Pull request closed without merging**
