### PR TITLE
Problem Suggestion: Add "grid path" to Bronze - Additional Practice for USACO Bronze

### PR DESCRIPTION
**Pull request by maggieliu05**
User `Q0gWnR4wZFVZiZHM5AacxQg0byD3` suggested adding the problem [grid path](https://cses.fi/problemset/task/1625) to the `problems` table of the module [Bronze - Additional Practice for USACO Bronze](https://usaco.guide/bronze/bronze-conclusion#problemlist-problems).

**Automatically Generated JSON:**
```json
{
  "uniqueId": "csa-GridPath",
  "name": "grid path",
  "url": "https://cses.fi/problemset/task/1625",
  "source": "CSA",
  "difficulty": "Very Hard",
  "isStarred": false,
  "tags": [],
  "solutionMetadata": {
    "kind": "autogen-label-from-site",
    "site": "CSA"
  }
}
```
**Additional Notes**: None

*This PR was automatically generated from a user-submitted problem suggestion on the USACO guide.*

### CODE REVIEW

**Comment by envyaims** [comment]
Make it silver hard

**Comment by SansPapyrus683** [comment]
wait bro didn't even make the problem id correctly :sob:

**Comment by ryanchou-dev** [comment]
yea this problem already has an internal solution. iirc it used to be in the bronze pruning module as insane but got orphaned.

**Comment by SansPapyrus683** [comment]
we prob removed it for a reason. close?

**Comment by ryanchou-dev** [comment]
guess so

see https://github.com/cpinitiative/usaco-guide/blob/a2c14e849a968bb723bad365e3f859fb115e5095/content/2_Bronze/Complete_Rec.problems.json

and https://github.com/cpinitiative/usaco-guide/blob/a2c14e849a968bb723bad365e3f859fb115e5095/content/2_Bronze/Complete_Rec.mdx?plain=1

**Pull request closed without merging**
