### PR TITLE
Problem Suggestion: Add " Little Alawn's Puzzle" to Silver - (Optional) Introduction to Functional Graphs

### PR DESCRIPTION
**Pull request by jeffkmeng**
User `urZ5lHZuCwWham5xM8h2Ov4q6Kz1` suggested adding the problem [ Little Alawn's Puzzle](https://codeforces.com/contest/1534/problem/C) to the `probs` table of the module [Silver - (Optional) Introduction to Functional Graphs](https://usaco.guide/silver/func-graphs#problemlist-probs).

**Automatically Generated JSON:**
```json
{
  "uniqueId": "cf-1534C",
  "name": " Little Alawn's Puzzle",
  "url": "https://codeforces.com/contest/1534/problem/C",
  "source": "CF",
  "difficulty": "Normal",
  "isStarred": false,
  "tags": [
    "Functional Graph",
    "Modular Arithmetic"
  ],
  "solutionMetadata": {
    "kind": "autogen-label-from-site",
    "site": "CF"
  }
}
```
**Additional Notes**: None

*This PR was automatically generated from a user-submitted problem suggestion on the USACO guide.*

### CODE REVIEW

**Review by dongliu0426 — APPROVED** [review]
there's not a lot of problems in this module so, sure

**Comment by dongliu0426** [comment]
todo: move to extraproblems

**Comment by bqi343** [comment]
how is this a functional graph?

**Comment by dongliu0426** [comment]
https://codeforces.com/contest/1534/submission/119346517

**Comment by bqi343** [comment]
yes, the graph decomposes into cycles, which technically counts as a functional graph. But the functional graph module is supposed to be about graphs that don't decompose into cycles

**Pull request closed without merging**
