### PR TITLE
Add Maximize Value of Function for a Ball Passing Game

### PR DESCRIPTION
**Pull request by Pramad712**
This module has just 3 problems, it's best if it's moved here.

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x ] I have tested my code.
- [ x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ x] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by Pramad712** [comment]
see https://github.com/cpinitiative/usaco-guide/pull/4063 to find where it'll be deleted (these two pull requests go with each other)

**Comment by ryanchou-dev** [comment]
just close the other pr and do the change here.

you can switch to this branch after cloning / or even through the github web app and find the file and use the web edit tool.

**Comment by ryanchou-dev** [comment]
also, taking a quick look -- this problem seems more like a standard binary lifting problem than a functional graph problem, so likely out of scope for this module

**Comment by Pramad712** [comment]
binary lifting is technically functional graphs

**Comment by dongliu0426** [comment]
also I believe there exists a solution without binary lifting that involves doing casework on the functional graph, which might be a bit more appropriate for silver

**Comment by SansPapyrus683** [comment]
@dongliu0426 @ryanchou-dev so what yall think of this problem
put in bin lifting or use the scuffed casework sol

**Comment by ryanchou-dev** [comment]
i think if the author can put in an internal solution for the one with casework, that'd be preferred...

otherwise, i feel like a lot of people attempting the problem will get lost doing it + reading the editorial (?)

**Comment by Pramad712** [comment]
I'll close it for now until I get the solution.

**Comment by Pramad712** [comment]
Actually, I don't think it's possible without binary lifting. The problem is that you can have a component with:

1. A cycle
2. Multiple lines of nodes that connect to this cycle
3. There are multiple connecting nodes

For example:
image

It's very hard to find and make sure the component is completely found. For example, doing a dfs or bfs starting from node 5 in this graph won't detect the other "branches" from the cycle (e.g. 11, 12, 8, 9). This is because functional graphs are directed.

**Comment by Pramad712** [comment]
So, probably the binary lifting plat module.

**Pull request closed without merging**
