### PR TITLE
Add exercise to knapsack problem list

### PR DESCRIPTION
**Pull request by dongliu0426**

### CODE REVIEW

**Comment by frodakcin** [comment]
Actually, it's already in the DP w/ Number Theory section.
@bqi343 opinion?

**Comment by bqi343** [comment]
tbh could move most of DP NT back to knapsack and scrap that module ...

**Comment by thecodingwizard** [comment]
yeah, I'm down to do that

**Comment by bqi343** [comment]
Done in 8c0158b.

**Pull request closed without merging**
