### PR TITLE
Problem Suggestion: Add "Beach Umbrellas" to Platinum - Binary Jumping

### LINKED ISSUE #1123: Problem Suggestion: Add "Beach Umbrellas" to Platinum - Binary Jumping
*James Kingy* (UID QmwK0DbHpzUS55KqhCBAXtLcSbC2) suggested adding the problem [Beach Umbrellas](https://orac2.info/problem/aio20beach/) to the module [Platinum - Binary Jumping](https://usaco.guide/plat/bin-jump#problemlist-general).

**Difficulty**: Hard
**Tags**: Binary Jumping
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

### PR DESCRIPTION
**Pull request by jeffkmeng**
*Problem Suggestion Issue Migration Bot* (UID PROB_SUGG_MIGRATE_BOT) suggested adding the problem [Beach Umbrellas](https://orac2.info/problem/aio20beach/) to the `general` table of the module [Platinum - Binary Jumping](https://usaco.guide/plat/bin-jump#problemlist-general).

**Automatically Generated JSON:**
```json
{
  "uniqueId": "other-BeachUmbrellas",
  "name": "Beach Umbrellas",
  "url": "https://orac2.info/problem/aio20beach/",
  "source": "other",
  "difficulty": "Hard",
  "isStarred": false,
  "tags": [
    "Binary Jumping"
  ],
  "solutionMetadata": {
    "kind": "none"
  }
}
```
**Additional Notes**:
None
(Closes #1123)

**Warning: The source of this problem is currently set to `other`. You must correct the problem source and the solution before merging.**
*This PR was automatically generated from a user-submitted problem suggestion on the USACO guide.*

### CODE REVIEW

**Comment by frodakcin** [comment]
I don't want to deal with this D:

**Comment by HarryWangATX** [comment]
wut happened to this xD

**Comment by thecodingwizard** [comment]
@SansPapyrus683 LOL what happened here?

**Comment by HarryWangATX** [comment]
> @SansPapyrus683 LOL what happened here?

this looks horrifying xD

**Comment by SansPapyrus683** [comment]
WHAT DID I DO

**Comment by andrewwangva** [comment]
im gonna just close this that idt this problem actually needs bin-jumping but I also don't know what @SansPapyrus683 was doing.

**Comment by SansPapyrus683** [comment]
i seriously didn't do anything

**Pull request closed without merging**
