### PR TITLE
Fix for issue #2155 - Quiz Component Improvements

### PR DESCRIPTION
**Pull request by topshenyi-web**
Added Features
- Previous quiz answers are now saved
- Your answer can be changed after pressing submit (excluding a correct answer submission)
- The explanation for only the selected answer is shown (if it exists)
- You can deselect an answer choice by clicking on it again. 
- You can skip questions

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code. 
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

### CODE REVIEW

**Comment by topshenyi-web** [comment]
Disregard the LIS commit... That was from years ago lol

**Comment by SansPapyrus683** [comment]
i take it you tested this?

**Comment by topshenyi-web** [comment]
@SansPapyrus683 I guess you can just find any module with a quiz in it?

**Comment by SansPapyrus683** [comment]
no need to revert LIS stuff, that's fine

**Review by maggie-j-liu — CHANGES_REQUESTED** [review]
looks good! would you also be able to implement this
> it shouldn't be necessary to answer a question before proceeding to the next.

and also revert the changes to `src/pages/groups.tsx` when you're done

**Comment by topshenyi-web** [comment]
@maggie-j-liu Yeah sure! I'll do that soon

**Review by maggie-j-liu — APPROVED** [review]
thank you!

**Pull request merged**
