### PR TITLE
Animation for Convex Hull

### PR DESCRIPTION
**Pull request by brebenelmihnea**
_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
get dustin and ryan to approve

**Comment by dustin-miao** [comment]
The colors of the convex hull don't make sense in the context of the algorithm, since it maintains the current hull for the first $i$ points, so from the perspective of the algorithm it doesn't know which points will be on the global hull. You could change this to have the edges turn red when they get removed, similar to the first video in the module.

**Comment by dustin-miao** [comment]
Also, there's two overlapping points on the far right side, it's better if this is removed.

**Comment by brebenelmihnea** [comment]
Ok

**Comment by brebenelmihnea** [comment]
@dustin-miao I made the changes

**Comment by brebenelmihnea** [comment]
@ryanchou-dev please review

**Review by ryanchou-dev — COMMENTED** [review]
i don't know convex hull too well, sorry.

**Comment by brebenelmihnea** [comment]
Ok ! @dustin-miao please review

**Review by dustin-miao — APPROVED** [review]
Ok, looks good.

**Comment by brebenelmihnea** [comment]
@SansPapyrus683  can you approve now ?

**Comment by Aadit-Ambadkar** [comment]
Okay but... who has the attention span to watch the entire thing.

My suggestion is speed it up to 2x or even 5x

**Review by ryanchou-dev — APPROVED** [review]
🔅🔅

**Comment by ryanchou-dev** [comment]
looks great! get one more approval and ill merge 🎄

**Comment by brebenelmihnea** [comment]
Ok

**Comment by SansPapyrus683** [comment]
no one looks at these modules anyways :sob:

**Comment by brebenelmihnea** [comment]
> no one looks at these modules anyways 😭
😭

**Pull request merged**
