### PR TITLE
Problem Suggestion: Add "Stone Game" to Advanced - Game Theory

### PR DESCRIPTION
**Pull request by jeffkmeng**
User `2wDctdng2ua1OH4TlE6ClSu3MZs1` suggested adding the problem [Stone Game](http://usaco.org/index.php?page=viewproblem2&cpid=1113) to the `general` table of the module [Advanced - Game Theory](https://usaco.guide/adv/game-theory#problemlist-general).

**Automatically Generated JSON:**
```json
{
  "uniqueId": "usaco-1113",
  "name": "Stone Game",
  "url": "http://usaco.org/index.php?page=viewproblem2&cpid=1113",
  "source": "Bronze",
  "difficulty": "Easy",
  "isStarred": false,
  "tags": [
    "Game Theory",
    "Number Theory"
  ],
  "solutionMetadata": {
    "kind": "USACO",
    "usacoId": 1113
  }
}
```
**Additional Notes**: None

*This PR was automatically generated from a user-submitted problem suggestion on the USACO guide.*

### CODE REVIEW

**Comment by jeffarjeffar** [comment]
Wait what I meant to select USACO Gold...

**Comment by jeffarjeffar** [comment]
Bruh in dark theme u can't see the source list clearly

image

**Comment by thecodingwizard** [comment]
@jeffreymeng

**Comment by Aryansh-S** [comment]
duplicate; I already made this PR lol

**Comment by jeffarjeffar** [comment]
> duplicate; I already made this PR lol

oh oops.
It would be nice if you could fix the dark theme issue though

**Comment by jeffreymeng** [comment]
it should have already been fixed

**Comment by jeffreymeng** [comment]
I'll close since #1245 tracks the same thing

**Pull request closed without merging**
