### PR TITLE
Added APIO 2009 - Oil solution

### PR DESCRIPTION
**Pull request by xyzyzl**
Also fixed LMIO 2019 - Triusis solution

### CODE REVIEW

**Comment by bqi343** [comment]
Wasn't Trusis okay before?

**Comment by dolphingarlic** [comment]
There are official solutions to the APIO 2009 problems, so I think you should link to those as well

**Comment by xyzyzl** [comment]
> Wasn't Trusis okay before?

i think it said specifically i_1, when it could be said for any i_j

**Comment by bqi343** [comment]
But saying it for i_1 is sufficient (when combined with the other condition).

**Comment by thecodingwizard** [comment]
Can we change it back to `i_1` and then merge this?

**Comment by bqi343** [comment]
It's fine both ways :P

**Comment by thecodingwizard** [comment]
ok perfect then I'll just merge this as is :)

**Pull request merged**
