### PR TITLE
Started the interactive module

### PR DESCRIPTION
**Pull request by dolphingarlic**
Should I add more problems? I could totally just refer the reader to https://oj.uz/problems?search=&type=INTERACTIVE though...

### CODE REVIEW

**Comment by dolphingarlic** [comment]
Are all the tips fine?

**Comment by bqi343** [comment]
Sure.

**Comment by bqi343** [comment]
I don't think "saveit" should be spoiled though :)

**Comment by bqi343** [comment]
I don't rlly agree with these difficulties ("Kanji Shiritori" doesn't seem harder than "Stray Cat") but ok for now

**Pull request merged**
