### PR TITLE
Groups Templating System

### PR DESCRIPTION
**Pull request by MrinallU**
- Implement Template System
- Format 7ca952a
- Implement Template System
- Remove function
- merge content changes
- feat: individual problem templating system
- format fixes
- wip: reformat assignment export code

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

### CODE REVIEW

**Comment by MrinallU** [comment]
@thecodingwizard Fixed step 3 as detailed in #2594.

**Comment by SansPapyrus683** [comment]
wow it's been ages since another web dev pr

**Comment by MrinallU** [comment]
> wow it's been ages since another web dev pr

Life has been keeping me busy, I'm back now though.

**Comment by SansPapyrus683** [comment]
so what's there to review?

**Comment by MrinallU** [comment]
> so what's there to review? if you tested it yourself, should i just merge? @maggie-j-liu?

Nah, Nathan wanted the code to be more efficient.

**Comment by MrinallU** [comment]
But it should be ready now, just waiting for his review

**Comment by SansPapyrus683** [comment]
how would you theoretically optimize this

**Comment by MrinallU** [comment]
> how would you theoretically optimize this

So in regards to this issue, one thing that I was doing was querying all the groups at the head of the component. This led to all of the groups being queried whenever the user opened a group, rather than when the user actually intended to transfer an assignment from one group to another, causing a lot of unnecessary queries. By querying the groups only when the user opens the export assignment modal, we can reduce the number of queries being executed drastically, thus optimizing the program.

**Comment by SansPapyrus683** [comment]
wow that's really thought out
so have you implemented that already?

**Comment by MrinallU** [comment]
> wow that's really thought out so have you implemented that already?

yea, but trust me it's not complex at all lol.

**Comment by MrinallU** [comment]
web dev optimization vs typical cp optimization do have some similarities but are fairly different.

**Review by maggie-j-liu — APPROVED** [review]
looks good; @thecodingwizard what do you think?

**Comment by thecodingwizard** [comment]
👀 ok sure, I didn't look too closely but it seems fine!

**Pull request merged**
