### PR TITLE
Refactor usaco 619 cpp solution

### PR DESCRIPTION
**Pull request by RmdanJr**
rewrite the pos_of_interest function in a cleaner way.

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
don't feel like this is necessary, how is it cleaner?

**Comment by RmdanJr** [comment]
@SansPapyrus683 
The function returns the list of *important* coordinates. The current implementation loop through all coordinates and stores distinct ones in `distinct` vector and their indices in `num_left` vector. Then loop through all distinct elements in `distinct` vector and add the element to returned `important` vector only if its index in the original `pos` array is between `pos.size() / 3` and `2 * pos.size() / 3`.
Why all this if we could loop through elements in `pos` from `pos.size() / 3` and `2 * pos.size() / 3` and add an element to returned `important` vector if it's distinct. This is what I did. I think this is more cleaner, has fewer steps, and is easy to understand.

**Comment by SansPapyrus683** [comment]
cool, but why change all the other things like the `using`s?

**Comment by RmdanJr** [comment]
I just changed them to make the code shorter. But improving `the pos_of_interest()` function was my main goal.

**Comment by SansPapyrus683** [comment]
can you revert those other changes?

**Comment by RmdanJr** [comment]
Sure. Reverted.

**Comment by bqi343** [comment]
Actually, this solution is wrong; it outputs 3 on this input:

```
3
1 7
5 1
7 9
```

Will revert to the previous solution.

**Pull request merged**
