### PR TITLE
update script to https

### PR DESCRIPTION
**Pull request by danielzsh**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by danielzsh** [comment]
@thecodingwizard any idea why this doesn't work? python can't fetch https://usaco.org/current/data/dec23_gold_results.html properly, but javascript fetch can?

**Comment by thecodingwizard** [comment]
What do you mean by "doesn't work"?

Maybe USACO's ddos protection (cloudflare) thinks we're trying to ddos them. That would be very, very annoying.

**Comment by danielzsh** [comment]
`urllib.request.urlopen('https://usaco.org/current/data/dec23_gold_results.html')` causes a 403 Forbidden Error, while `fetch('https://usaco.org/current/data/dec23_gold_results.html')` works fine. After some googling, others have had issues with urlopen and https but none of the fixes they mentioned worked...

**Review by thecodingwizard — APPROVED** [review]
lgtm!

**Comment by danielzsh** [comment]
wait it still doesn't work though 😭

**Comment by thecodingwizard** [comment]
oh.. what if you try a different library, like requests? https://pypi.org/project/requests/ (You are running locally, not on Github Actions, right?)

**Comment by mjh316** [comment]
```py
import urllib
req = urllib.request.Request(url, headers={'User-Agent' : "Magic Browser"}) 
con = urllib.request.urlopen( req )
print(con.read())
```
Have you tried this fix from [here](https://stackoverflow.com/a/3336735/16730900)? Seems to work locally for me.

**Comment by danielzsh** [comment]
works for me locally too, lets hope it works on gh actions 🙏

**Review by thecodingwizard — APPROVED** [review]
lgtm!

**Comment by danielzsh** [comment]
wait what, the workflow on master suddenly started working again 😭 
https://github.com/cpinitiative/usaco-guide/actions/runs/8088739231/job/22103377324

**Pull request merged**
