### PR TITLE
add translation again

### PR DESCRIPTION
**Pull request by SansPapyrus683**
_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [x] I have tested my code
- [x] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [x] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
image
fail the build, i fricking dare you

**Comment by SansPapyrus683** [comment]
image
the suspense is killing me

**Comment by SansPapyrus683** [comment]
LET'S HECKING GOOOO

**Review by maggie-j-liu — APPROVED** [review]

**Review by ryanchou-dev — APPROVED** [review]
yesssss

**Review by TruaShamu — APPROVED** [review]
yay

**Review by Aadit-Ambadkar — CHANGES_REQUESTED** [review]
im picky

**Review by nathangong — APPROVED** [review]

**Comment by SansPapyrus683** [comment]
given 4 approvals and 1 request that i addressed, i'm just gonna merge this one

**Pull request merged**
