### PR TITLE
POI Maximal editorial

### PR DESCRIPTION
**Pull request by dolphingarlic**
Closes https://github.com/cpinitiative/usaco-guide/issues/383

### CODE REVIEW

**Comment by dolphingarlic** [comment]
Also I feel like this problem should be marked at least as "Hard". Limiting the primes wasn't very obvious, only one person solved it in-contest, and the official editorial is like 10 pages long

**Comment by bqi343** [comment]
Why nlogn? (If you include all prime powers along with primes, then you'll still have < 1300 total).

**Comment by bqi343** [comment]
You don't need to limit the primes (I used a bitset).

```py
array<ld,10001> ans, tmp;
bitset<10001> z[1300];
bool pri[10001];
vi co, CO;

void fin(int x) {
    pi cur = {x,sz(co)-1};
    vi zz;
    int lastUse = 0;
    while (cur.s != -1) {
        if (z[cur.s][cur.f] && lastUse != CO[cur.s]) {
            lastUse = CO[cur.s];
            cur.f -= co[cur.s]; zz.pb(co[cur.s]);
        }
        cur.s --;
    }
    sort(all(zz));
    int sum = 0; trav(t,zz) sum += t;
    vi ret;
    sum = x-sum;
    F0R(i,sum) ret.pb(i+1);
    trav(t,zz) {
        FOR(j,sum,sum+t-1) ret.pb(j+2);
        ret.pb(sum+1);
        sum += t;
    }
    trav(z,ret) pr(z,' ');
    ps();
}

int main() {
    setIO(); 
    int d; re(d); vi v(d); re(v);
    int mx = 0; trav(t,v) ckmax(mx,t);
    FOR(i,2,mx+1) pri[i] = 1;
    F0R(i,mx+1) ans[i] = 1;
    FOR(i,2,mx+1) if (pri[i]) {
        tmp = ans;
        for (int j = 2*i; j <= mx; j += i) pri[j] = 0;
        for (int j = 1; pow(i,j) <= mx; j ++) {
            int x = pow(i,j);
            FOR(k,x,mx+1) {
                if (x*ans[k-x] > tmp[k]) {
                    tmp[k] = x*ans[k-x];
                    z[sz(co)][k] = 1;
                    // ps("WUT",sz(co),k);
                }
            }
            co.pb(x); CO.pb(i);
        }
        swap(ans,tmp);
    }
    trav(x,v) fin(x);
}
```

**Comment by bqi343** [comment]
Also, DP_NT no longer exists, merged with knapsack.

**Review by bqi343 — CHANGES_REQUESTED** [review]
DP_NT no longer appears on website, merged with knapsack.

**Comment by dolphingarlic** [comment]
> Why nlogn? (If you include all prime powers along with primes, then you'll still have < 1300 total).

Isn't it n(log2 n + log3 n + ...) because you go through each prime power? If not, is it just O(n) with a big constant?

**Comment by bqi343** [comment]
Number of prime powers <= n is bounded above by n :)

**Pull request merged**
