### PR TITLE
Problem Suggestion: Add "Alchemy" to Bronze - Additional Practice for USACO Bronze

### PR DESCRIPTION
**Pull request by maggieliu05**
User `rbt9AstgJRayjZAO5TbyYDBqX523` suggested adding the problem [Alchemy](http://usaco.org/index.php?page=viewproblem2&cpid=1229) to the `problems` table of the module [Bronze - Additional Practice for USACO Bronze](https://usaco.guide/bronze/bronze-conclusion#problemlist-problems).

**Automatically Generated JSON:**
```json
{
  "uniqueId": "usaco-1229",
  "name": "Alchemy",
  "url": "http://usaco.org/index.php?page=viewproblem2&cpid=1229",
  "source": "Bronze",
  "difficulty": "Hard",
  "isStarred": false,
  "tags": [
    "DFS",
    "Recursion",
    "Greedy",
    "Tree"
  ],
  "solutionMetadata": {
    "kind": "USACO",
    "usacoId": "1229"
  }
}
```
**Additional Notes**:
This problem is very recent and difficult, as it is from the 2022 US Open. It is part of an "array-computation" greedy type that is new and shown in the 2021-2022 season.

*This PR was automatically generated from a user-submitted problem suggestion on the USACO guide.*

### CODE REVIEW

**Comment by Pramad712** [comment]
Solution: http://usaco.org/current/data/sol_prob3_bronze_open22.html

**Comment by SansPapyrus683** [comment]
this is already in the guide?

**Comment by bqi343** [comment]
^

**Comment by Pramad712** [comment]
I don't see it in the guide. It is only in the "USACO Monthlies" but not in an actual module.

**Comment by bqi343** [comment]
you can search for it in https://usaco.guide/problems/

**Pull request closed without merging**
