### PR TITLE
Add Floodfill Warning

### PR DESCRIPTION
**Pull request by brad182**
This issue has happened to me so many times where making the matrix just a little bit bigger gets you the rest of the test cases. The module does not currently mention this.

### CODE REVIEW

**Comment by caoash** [comment]
I've never had this happen to me. Aren't the borders for floodfill problems usually blocked, so making the grid larger would make cells that shouldn't be flooded be flooded?

Can you give an example of when this would happen?

**Comment by maggie-j-liu** [comment]
would this https://usaco.guide/problems/usaco-596-build-gates/solution be a good example?

**Comment by brad182** [comment]
> I've never had this happen to me. Aren't the borders for floodfill problems usually blocked, so making the grid larger would make cells that shouldn't be flooded be flooded?
> 
> Can you give an example of when this would happen?

this happened to me quite a few times before, where changing the matrix size just a little bit bigger but not changing the algorithm gets you the rest of the test cases

yes, doing this in many cases will get the wrong answer which is why it is only done on some.

one example is on perimeter calculation:

######
##AA##
######

this is with the outer ring

###AA#
######
######

this is without the outer ring, if you try to calculate the perimeter using floodfill it will be 2 under because the places above the A's are not visited

a problem that I did that adding the outer ring fixed the test cases is this: http://www.usaco.org/index.php?page=viewproblem2&cpid=124

you do a floodfill inside a bfs, if you make the matrix perfectly N*N it will get the last test case wrong because the origin is actually reachable but the visiting is blocked off by bales on the edge of the matrix

**Comment by caoash** [comment]
That seems very problem-specific and probably not worth a warning? I think it's just a specific case of constructing the graph differently for some problems (which is a very general concept).

**Comment by brad182** [comment]
i'd say its quite common, maybe 30-40% of floodfill problems

**Comment by caoash** [comment]
Maybe I just got unlucky when I was practicing but I've never done this before (it could have to do with my implementation?)

For example, in the perimeter problem, you can probably just count the number of A's and then use that to compute the perimeter. For the tractor problem, can't you just run dijkstras? I don't actually see how floodfill is that useful.

**Comment by brad182** [comment]
> Maybe I just got unlucky when I was practicing but I've never done this before (it could have to do with my implementation?)
> 
> For example, in the perimeter problem, you can probably just count the number of A's and then use that to compute the perimeter. For the tractor problem, can't you just run dijkstras? I don't actually see how floodfill is that useful.
> 
> (Edit: I can see how it's useful for the tractor problem now, but I think that's just because you assume the grid is the size of the min/max x/y coordinates of the haybales. If the grid is unbounded I can see how this is useful, but I do think it's too specific and in most problems the edge of the grid isn't passable.)

it happens quite often to me though, hmm ill request review from others and see what they think

**Comment by maggie-j-liu** [comment]
idk, i don't think i ever forgot to make the grid larger, but there are problems that need the grid to be larger so you can floodfill outside too (i think this one https://usaco.guide/problems/usaco-596-build-gates/solution ?)

**Comment by SansPapyrus683** [comment]
i've never had this problem before lmao

**Comment by nathangong** [comment]
I've definitely run into cases where extending the grid makes the problem a lot easier, although there were also ways of solving it without doing so

**Comment by nwatx** [comment]
never had this problem but I've had cases where extending made it easier

**Comment by bqi343** [comment]
Agree with @caoash

**Pull request closed without merging**
