### PR TITLE
added cf edu thing

### LINKED ISSUE #2455: Broken Link (CF EDU)
Someone submitted the contact form!

**Module**: Silver - Binary Search
**Topic**: Typo / Broken Link
**Message**: 
https://codeforces.com/edu/course/2/lesson/6/1/practice leads to a "course not found" message

### PR DESCRIPTION
**Pull request by SansPapyrus683**
_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

should close #2455
let's see if this works

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
https://usaco-guide-cegtvui0w-cpinitiative.vercel.app/silver/binary-search?lang=cpp
wha, why isn't it working

**Comment by maggie-j-liu** [comment]
hii 

are you talking about the tooltip?

i found this https://github.com/cpinitiative/usaco-guide/blob/master/src/components/markdown/ResourcesList.tsx#L43 you might need to update that as well? I'm not too sure tho

**Comment by SansPapyrus683** [comment]
don't think so? there doesn't seem to be a section for notes and stuff

**Comment by SansPapyrus683** [comment]
ok finally, done

**Pull request merged**
