### PR TITLE
Added Main Icon

### LINKED ISSUE #333: Colors for Dropdown
> I think it would be nice to add a small color badge on all the dropdown options (complete, reading, solving, etc.). The quick visual recognition would immensely improve UX in that aspect -- which is a pretty big aspect, as I'm sure a lot of people use it for every single module. :)

### PR DESCRIPTION
**Pull request by MrinallU**
Resolved #333

### CODE REVIEW

**Comment by thecodingwizard** [comment]
can we use yarn.lock instead of package json?

**Comment by MrinallU** [comment]
@thecodingwizard Alright I removed that.

**Comment by MrinallU** [comment]
Oh wait don't merge

**Comment by thecodingwizard** [comment]
@MrinallU can you merge the master branch into this branch?

**Comment by MrinallU** [comment]
How would I do that?

**Comment by thecodingwizard** [comment]
```
git pull
git merge master
```

I think :O

**Comment by MrinallU** [comment]
Hmm how can I do it in github? As when i entered in the terminal everything say it is up to date.

**Comment by thecodingwizard** [comment]
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork this might help?

**Comment by MrinallU** [comment]
@thecodingwizard Ok it should work now.

**Comment by thecodingwizard** [comment]
I don't think it merged properly... there's still a merge conflict

**Comment by MrinallU** [comment]
Umm there aren't any errors in my code and everything works mine, how can I resolve the conflict?

**Comment by thecodingwizard** [comment]
The github master branch has changed since you last branched off it (for example, there's a "settings" modal now). you have to merge the updated master branch into this branch (https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)

**Comment by MrinallU** [comment]
@thecodingwizard Quick question, are you a senior in hs?

**Comment by thecodingwizard** [comment]
no, junior :)

**Comment by MrinallU** [comment]
@thecodingwizard Seems like everything works now!

**Comment by MrinallU** [comment]
Cool, Im a sophmore myself, how long did you spend learning to get this good?

**Comment by thecodingwizard** [comment]
Quite a long time. I don't think I'm good though; just lucky XD

Also, I made some changes before merging :)

**Pull request merged**
