### PR TITLE
Created video solution for problem 1086, 595

### PR DESCRIPTION
**Pull request by cskitty**

### CODE REVIEW

**Review by SansPapyrus683 — APPROVED** [review]
Very well made!

**Comment by nwatx** [comment]
I think it would be beneficial to have time complexity as well as method

**Comment by cskitty** [comment]
> I think it would be beneficial to have time complexity as well as method

Good suggestion, I will add it in future videos.

**Comment by nwatx** [comment]
> > I think it would be beneficial to have time complexity as well as method
> 
> Good suggestion, I will add it in future videos. 

I mean in the content file itself

**Pull request merged**
