### PR TITLE
support getting metadata from url

### PR DESCRIPTION
**Pull request by danielzsh**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

### CODE REVIEW

**Comment by danielzsh** [comment]
@SansPapyrus683 would you mind just testing out this "Add Problem" button
image
It supports cses, usaco, atcoder, and cf at the moment

**Comment by SansPapyrus683** [comment]
if it works on your end i'm just going to trust

**Comment by danielzsh** [comment]
i need one approval to merge though if u dont mind 😅

**Review by SansPapyrus683 — APPROVED** [review]

**Comment by SansPapyrus683** [comment]
merge at your own recognizance

**Pull request merged**
