### PR TITLE
Hashing Revamp

### PR DESCRIPTION
**Pull request by HaccerKat**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

This is a revamp to the hashing module which adds XOR Hashing. Due to the change, I changed some of the names and ids from String Hashing to just Hashing. If this is a problem, I can change it back.

### CODE REVIEW

**Comment by HaccerKat** [comment]
oops forgot to add comments

**Comment by HaccerKat** [comment]
if there are comments you want me to add i will do later

**Review by envyaims — APPROVED** [review]
wow cool beans

the explanations look fine

**Comment by SansPapyrus683** [comment]
image

uuuhhh

**Review by SansPapyrus683 — APPROVED** [review]

**Comment by SansPapyrus683** [comment]
now all that remains is to fix the build...

**Comment by HaccerKat** [comment]
crap some of the other modules have "string-hashing" as a prereq

**Comment by HaccerKat** [comment]
hmmmmmm still not working

**Comment by HaccerKat** [comment]
all that effort to change a name
one more reason why i will never become a web dev

**Comment by SansPapyrus683** [comment]
no it's mostly just gatsby sucking balls

**Pull request merged**
