### PR TITLE
hide TOC when length <= 1

### LINKED ISSUE #499: Disable TOC?
Screen Shot 2020-12-19 at 1 00 02 PM

Seems silly for the TOC to take up so much space when there are no sections. (This would probably apply to most solution pages.)

### PR DESCRIPTION
**Pull request by bqi343**
closes #499

### CODE REVIEW

**Comment by bqi343** [comment]
closes #203

**Comment by thecodingwizard** [comment]
are there any modules with toc <= 1?

**Comment by dongliu0426** [comment]
- https://usaco.guide/adv/matroid-isect
- https://usaco.guide/adv/game-theory
- https://usaco.guide/adv/dp-sos

**Review by thecodingwizard — APPROVED** [review]
seems fine to me. I have a big monitor so it actually looks better with the table of contents sidebar, but I guess it might be different for small monitors

**Pull request merged**
