### PR TITLE
Add Problem "Playing in a Casino" to Bronze - Intro to Sorting

### PR DESCRIPTION
**Pull request by Prithul123**
solution:
#include <bits/stdc++.h>
typedef long long ll;
#define all(x) (x).begin(), (x).end()
#define rall(x) (x).rbegin(), (x).rend()
using namespace std;
void sol();
int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    ll t = 1;
    cin >> t;
    while (t--)
    {
        sol();
    }
    return 0;
}
long long lcm(int a, int b)
{
    return (a / __gcd(a, b)) * b;
}
bool compare_col(const vector<int> &v1, const vector<int> &v2) {
    return v1[1] < v2[1];
}
void sol()
{
    ll n, m;
    cin >> n >> m;
    vector<vector<int>> a(n, vector<int>(m)), pre(n, vector<int>(m));
    for (ll i = 0; i < n; i++)
    {
        for (ll j = 0; j < m; j++)
        {
            cin >> a[i][j];
        }
    }
    // ? ? sort(a.begin(), a.end(), compare_col);
    ll ans=0;
    for (ll i = 0; i < m; i++)
    {
        vector<ll> temp;
        ll sum = 0;
        for (ll j = 0; j < n; j++)
        {
            temp.push_back(a[j][i]);
            sum+=a[j][i];
        }
        ll curr = 0;
        sort(temp.begin(), temp.end());
        for (ll j = 0; j < n; j++)
        {
            curr += temp[j];
            ans += abs((sum - curr) - (n - 1 - j) * temp[j]);
        }
    }
    // for (ll i = 0; i < m; i++)
    // {
    //     ll sum = 0;
    //     for (ll j = 0; j < n; j++)
    //     {
    //         sum += a[j][i];
    //         pre[j][i] = sum;
    //     }
    // }
    // for (ll i = 0; i < m; i++)
    // {
    //     for (ll j = 0; j < n; j++)
    //     {
    //         ans += abs(pre[n - 1][i] - pre[j][i] - (n - 1 - j) * a[j][i]);
    //         // cout << abs(pre[n - 1][i] - pre[j][i] - (n - 1 - j) * a[j][i]) << " ";
    //     }
    // }
    cout << ans << "\n";
}

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
> I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).

have you?

**Comment by Prithul123** [comment]
sorry, I'm still new to GitHub, I've written the .mdx file for the solution and wanted to ask how to add it to the solutions from my fork?

**Comment by ryanchou-dev** [comment]
Make sure you've read through the https://usaco.guide/general/contributing?lang=cpp modules, you can look at other [PRs](https://github.com/cpinitiative/usaco-guide/pull/3588) to verify that you're on the right track.

Let me know if you need more help!

---

Also, when adding new problems, we generally discourage just plain solutions. If you wouldn't mind, could you also write a problem editorial?

**Comment by ryanchou-dev** [comment]
oops, nevermind, i see what you mean.

click this button:
image

**Comment by Prithul123** [comment]
so should I get rid of this pr and start a new one?

**Comment by ryanchou-dev** [comment]
yes

**Pull request closed without merging**
