### PR TITLE
Remove banner

### PR DESCRIPTION
**Pull request by TanayB11**
Commented out top "free classes" banner code, feel free to merge this whenever you feel like.

### CODE REVIEW

**Comment by bqi343** [comment]
Is there any other link on USACO Guide to https://joincpi.org/ ?

**Comment by thecodingwizard** [comment]
No :P

**Comment by thecodingwizard** [comment]
Anyone have suggestions of where we can link joincpi?

**Comment by TanayB11** [comment]
I think it should go in the FAQ next to where we have the "Is this open source?" part. There's an empty space there that we could fill with a relevant question and link

**Comment by thecodingwizard** [comment]
just gonna remove it for now since signups from the banner are decreasing :P

**Pull request merged**
