### PR TITLE
dmoj problem labels?

### LINKED ISSUE #3756: DMOJ Contests have Inconsistent Labels
Certain links are inconsistent as to whether they're labelled "DMOJ" or the name of the contest they're originally from. For example, see the the [merging subtrees module](https://usaco.guide/editor/?filepath=content/6_Advanced/Comb_Sub.mdx) or [IOI Phidias](https://usaco.guide/problems/dmoj-phidias/solution). Most contests are labelled with the name of the competition, so I assume that's the correct way. 

Not sure if this is also true for other OJs. 

Tagging #3755

### PR DESCRIPTION
**Pull request by SansPapyrus683**
_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

*tries* to close #3756, probably fails tho

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
uh the editorial sources are still listed under dmoj so

**Comment by ryanchou-dev** [comment]
> uh the editorial sources are still listed under dmoj so
> 
> 
> 
> image
> 
> 
> 
> shouldn't it read from here

nah like on the problem table, the source name dont have the hover thing

likely fine, but just to be consistent

**Comment by SansPapyrus683** [comment]
ok just wait a lil

**Comment by SansPapyrus683** [comment]
image

ok i added dmopc, which like 80% of the problems come from

**Comment by ryanchou-dev** [comment]
ok sounds good... maybe someone from web dev could approve

**Pull request merged**
