### PR TITLE
Update USACO dec16-blockgame.mdx

### PR DESCRIPTION
**Pull request by tickox**

### CODE REVIEW

**Comment by bqi343** [comment]
Probably better to replace with the other suggested solution:

```cpp
#include <bits/stdc++.h>

void count_freq(const std::string &s, std::array<int, 26> &arr) {
  for (char c: s) {
    arr[c - 'a']++;
  }
}

int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(0);
  freopen("blocks.in", "r", stdin);
  freopen("blocks.out", "w", stdout);
  int n;
  std::cin >> n;
  std::array<int, 26> ans{};
  while (n--) {
    std::string s1, s2;
    std::cin >> s1 >> s2;
    std::array<int, 26> freq1{}, freq2{};
    count_freq(s1, freq1); count_freq(s2, freq2);
    for (int i = 0; i < 26; i++) {
      ans[i] += std::max(freq1[i], freq2[i]);
    }
  } 
  for (int i: ans) {
    std::cout << i << '\n';
  }
  
  return 0;
}
```

**Comment by thecodingwizard** [comment]
except preferably without the `std::` XD

**Comment by tickox** [comment]
UPDATE:

#include <bits/stdc++.h>

using namespace std;

constexpr int nb_letter = 26;
using ar = array<int, nb_letter>;

void count_freq(const string &s, ar &arr) {
  for (char c: s) {
    arr[c - 'a']++;
  }
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(0);
  freopen("blocks.in", "r", stdin);
  freopen("blocks.out", "w", stdout);
  int n;
  cin >> n;
  ar ans{};
  while (n--) {
    string s1, s2;
    cin >> s1 >> s2;
    ar freq1{}, freq2{};
    count_freq(s1, freq1); count_freq(s2, freq2);
    for (int i = 0; i < nb_letter; i++) {
      ans[i] += max(freq1[i], freq2[i]);
    }
  } 
  for (int i: ans) {
    cout << i << '\n';
  }
  
  return 0;
}

**Comment by tickox** [comment]
UPDATE:
```c++
#include <bits/stdc++.h>

using namespace std;

constexpr int nb_letter = 26;
using arr = array<int, nb_letter>;

void count_freq(const string &s, arr &arr) {
  for (char c: s) {
    arr[c - 'a']++;
  }
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(0);
  freopen("blocks.in", "r", stdin);
  freopen("blocks.out", "w", stdout);
  int n;
  cin >> n;
  arr ans{};
  while (n--) {
    string s1, s2;
    cin >> s1 >> s2;
    arr freq1{}, freq2{};
    count_freq(s1, freq1); count_freq(s2, freq2);
    for (int i = 0; i < nb_letter; i++) {
      ans[i] += max(freq1[i], freq2[i]);
    }
  } 
  for (int i: ans) {
    cout << i << '\n';
  }
  
  return 0;
}
```

**Comment by bqi343** [comment]
Also update the author in frontmatter

**Pull request merged**
