### PR TITLE
Studying Algorithms

### LINKED ISSUE #721: Add https://usaco.guide/silver/greedy?lang=cpp#example-studying-algorithms to codeforces gym?

### PR DESCRIPTION
**Pull request by dongliu0426**
closes #721

### CODE REVIEW

**Comment by frodakcin** [comment]
I'm reading the module here https://usaco-guide-nmydjsszn.vercel.app/silver/greedy?lang=cpp and think it might be better to copy the statement in the guide as well as providing a submission link.

**Comment by frodakcin** [comment]
What do you think? Also the code isn't copy-pastable complete -- let's see if people struggle to solve in on cf to see if we need to change that.

**Comment by frodakcin** [comment]
> I'm reading the module here https://usaco-guide-nmydjsszn.vercel.app/silver/greedy?lang=cpp and think it might be better to copy the statement in the guide as well as providing a submission link.

I guess this would be impractical for certain problems, especially those with long statements, but I think in this case it may be preferable

**Comment by frodakcin** [comment]
@HarryWangATX @andrewwangva Ready for review now (I probably should have marked as draft earlier)

**Comment by HarryWangATX** [comment]
Alr reviewing

**Review by HarryWangATX — APPROVED** [review]
Looks good lol

**Pull request merged**
