### PR TITLE
Fix Kattis contest links to problems

### PR DESCRIPTION
**Pull request by megargayu**
The two links changed, https://open.kattis.com/contests/acpc17open/problems/laneswitching and https://open.kattis.com/contests/mcpc19open/problems/basketballoneonone, do not allow submitting (they give an error when submitting). However, the new links, https://open.kattis.com/problems/laneswitching and https://open.kattis.com/problems/basketballoneonone respectively, do allow submitting. The problems are the exact same, just the links are different so they actually allow submitting. 

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

### CODE REVIEW

**Comment by maggie-j-liu** [comment]
hi! [it](https://open.kattis.com/contests/acpc17open/problems/laneswitching) does seem to allow submitting? can you send what you see?
image

**Comment by SansPapyrus683** [comment]
OH NO I ALR MERGED

**Comment by maggie-j-liu** [comment]
dw we can revert 😅 what do you see on the links?

**Comment by megargayu** [comment]
@maggie-j-liu @SansPapyrus683 When you try to click "submit", it gives an alert saying you have to join the contest - for example, on Chrome, it shows this:

Error: Your team needs to join the contest in order to be allowed to submit.

However, on the new links, it doesn't give this error and allows submission.

**Comment by maggie-j-liu** [comment]
ah makes sense, thanks!

**Pull request merged**
