### PR TITLE
Expandable Sidebar

### PR DESCRIPTION
**Pull request by MrinallU**

### CODE REVIEW

**Comment by MrinallU** [comment]
@thecodingwizard Where is vercel?

**Comment by MrinallU** [comment]
@thecodingwizard This library isn't compatible with the guide :(  I will have to try something else.

**Comment by MrinallU** [comment]
@thecodingwizard Wait actually nvm, I was being dumb.

**Comment by thecodingwizard** [comment]
closing as stale :)

**Pull request closed without merging**
