### PR TITLE
spaced out hint

### PR DESCRIPTION
**Pull request by ryanchou-dev**
_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
hb for a hint 2 you give them the sample cases

**Review by envyaims — COMMENTED** [review]
id consider this half a hint at most
Just a personal opinion but i think hints should learn more towards the "give-away" side. I remember as I was starting out I'd be frustrated if I read hints that meant borderline nothing and just open more and eventually read the solution anyways

**Comment by ryanchou-dev** [comment]
ok! will do when i get home

**Review by SansPapyrus683 — APPROVED** [review]
@envyaims your problem

**Review by envyaims — APPROVED** [review]
interesante mucho

**Pull request merged**
