### PR TITLE
Problem Feedback 

### PR DESCRIPTION
**Pull request by thecodingwizard**
Carried over from #489 

Thanks Mrinall!

### CODE REVIEW

**Comment by dolphingarlic** [comment]
In dark mode, the text is white :(

**Comment by dolphingarlic** [comment]
The "Problem Difficulty" section is missing "Very Hard"

**Comment by thecodingwizard** [comment]
Big anger, I'll fix tomorrow

**Comment by thecodingwizard** [comment]
Oh also -- there should be an option to choose what language your code submission is in

**Comment by MrinallU** [comment]
@thecodingwizard Some people may want some credit for their solution so perhaps they should have the option make themselves anonymous or not.

**Comment by MrinallU** [comment]
> Carried over from #489
> 
> Thanks Mrinall!

No problem! I'll be working on some other issues as well.

**Comment by MrinallU** [comment]
@thecodingwizard Is it ready?

**Comment by thecodingwizard** [comment]
:pray: I hope this works LMAO

**Pull request merged**
