### PR TITLE
+ Bronze tags, move some problems

### PR DESCRIPTION
**Pull request by bqi343**
- I wouldn't consider Social Distancing 1 to be greedy, it's just casework ...
- There's a greedy aspect to "Spaced Out" but I think it makes more sense to place it in "Ad Hoc"?

### CODE REVIEW

**Comment by HarryWangATX** [comment]
https://github.com/cpinitiative/usaco-guide/pull/664 Didnt we place spaced out in greedy for a reason?

**Comment by bqi343** [comment]
nope that was a terrible reason

**Comment by HarryWangATX** [comment]
> I take that back, that was not a good reason :/

yea xD

**Comment by bqi343** [comment]
@thecodingwizard not sure how to fix this (the spacing, + making the nested list unordered and not a continuation of the ordered list)

Screen Shot 2021-02-09 at 12 37 03 PM

**Comment by thecodingwizard** [comment]
You can do nested ordered lists like this:

image

Full (formatted) file in case it's helpful:

```
---
id: contributing
title: Contributing
author: Nathan Wang, Benjamin Qi
description: How to contribute!
prerequisites:
  - modules
---

Note that the USACO Guide has a public [Github Repository](https://github.com/cpinitiative/usaco-guide). Feel free to contribute by submitting issues and Pull Requests!

**Please help fix some of the [issues](https://github.com/cpinitiative/usaco-guide/issues) on our Github Repository!**

<!--
If you're interested in joining the team, please fill out this [Google form](https://docs.google.com/forms/d/e/1FAIpQLSew7yq-8osY-IAxHRXX0_g-C747t7778aDuz-Crz6f77AuABA/viewform?usp=sf_link). -->

<!-- Please use the "Contact Us" form to get started and mention **what specifically you intend to contribute**.  -->

## Ways to Contribute

Some examples:

### Lesson

- Convert lists of resources to tables (Plat / Advanced).
- Add missing descriptions for sections, modules, or resources.
  - All resources should have descriptions.
- Improve explanations for sample problems.
  - If starred resource or editorial already has a good explanation, no need to repeat it.
- Improve implementations.
  - Include code handling input & output.
  - Should be consistent across languages.
- Adding modules!

### Problems

- Convert lists of problems to tables (Plat / Advanced).
- Fix problem difficulties and tags.
- Add problems that are good examples of the module topic (and remove those that are not).
- Adding official editorial links.
  - Those for USACO are automatically generated.
- Adding editorials.
  - If no editorial exists, or if existing editorial could be improved.
  - Or solution code in a different language, etc.

<!-- - Don't link CF if it's already included in "Contest Materials." -->

## Writing Content

All modules are written in [MDX](https://mdxjs.com/) (Markdown + JSX), with limited $\LaTeX$ support from [KaTeX](https://katex.org/) and some custom components. You can check how an `.mdx` file renders by pasting it in the [live editor](/liveupdate).

See the [Content Documentation](https://github.com/cpinitiative/usaco-guide/blob/master/docs/Content%20Documentation.md) for more info.

### Useful Links

- [Markdown Cheat Sheet](https://www.markdownguide.org/cheat-sheet/)
- [Markdown Table Generator](https://www.tablesgenerator.com/markdown_tables)
- [StackEdit](https://stackedit.io/)
  - nice markdown editor
  - supports Katex
- [Sublime Text](https://www.sublimetext.com/)
  - `.md` syntax highlighting is fine, is also ok for `.mdx`
  - You can open a `.mdx` file and set syntax highlighting to be the same as `.md` with `View -> Syntax -> Open all with current extension as ... -> Markdown -> Markdown`.

### Adding a Solution

1. [Fork](https://docs.github.com/en/free-pro-team@latest/desktop/contributing-and-collaborating-using-github-desktop/cloning-and-forking-repositories-from-github-desktop) the GitHub repository.

2. If it doesn't already exist, create a new `mdx` file in `solutions` including frontmatter, ex. the following in [`USACO jan17-cow-dance-show.mdx`](https://github.com/cpinitiative/usaco-guide/blob/master/solutions/USACO%20jan17-cow-dance-show.mdx):

	```
	---
	id: usaco-690
	source: USACO Silver 2017 January
	title: Cow Dance Show
	author: Óscar Garries
	---

	[Official Analysis](http://www.usaco.org/current/data/sol_cowdance_silver_jan17.html)

	<LanguageSection>

	<CPPSection>

	**Time Complexity:** $\mathcal{O}(N\log^2N)$

	^ Format time complexity like this.

	(add C++ code + explanation here ...)

	Use `\texttt{}` around variable names with length greater than one, like so. Place long equations on separate lines with display math, and use `\cdot` instead of `*` to denote multiplication.

	$$
	\texttt{arr}[i]=2\cdot (a+b+c+d+e)+\sum_{j=0}^{i-1}\texttt{arr}[j]
	$$

	</CPPSection>

	<PySection>

	(if you have Python code)

	</PySection>

	<JavaSection>

	(if you have Java code)

	</JavaSection>

	</LanguageSection>
	```

	Keep file names and solution IDs consistent; namely, USACO IDs should correspond to the URL on [usaco.org](http://www.usaco.org/index.php?page=viewproblem2&cpid=690). It is **not** necessary to add an alternative implementation in the same language as the official analysis (unless the alternative implementation takes a different approach or is written better / differently from the official implementation).

3. Code conventions:
	1. Use _tabs_ to indent.
	2. Don't use too many [macros](/general/generic?lang=cpp#macros).
	3. Lines should not exceed 80 characters.

4. Add the solution ID (ex. `usaco-690`) as the last argument of the `Problem` constructor in the corresponding module (in this case, [`Binary_Search_Ans.mdx`](https://github.com/cpinitiative/usaco-guide/blob/master/content/3_Silver/Binary_Search_Ans.mdx)). Also add tags (if you want).

	```
	new Problem(
	'Silver',
	'Cow Dance Show',
	'690',
	'Easy',
	false,
	['tag1', 'tag2'],
	'usaco-690'
	),
	```

5. Check that both the module and the solution render properly using the [live editor](/liveupdate/) before submitting a [pull request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests).
```

**Comment by bqi343** [comment]
What about making the inner list unordered?

**Review by Farrius — APPROVED** [review]

**Comment by Farrius** [comment]
Looks good to me. Although I am not sure about changing 'single loop' and 'nested loop' to just 'simulation', putting just 'simulation' is cleaner. On the other hand knowing if the loop is nested or not might be a good hint if somebody is trying to solve the problem.

**Comment by bqi343** [comment]
> Looks good to me. Although I am not sure about changing 'single loop' and 'nested loop' to just 'simulation', putting just 'simulation' is cleaner. On the other hand knowing if the loop is nested or not might be a good hint if somebody is trying to solve the problem.

Only two of the problems were tagged with "single loop," so I didn't think including that tag was useful. Besides, if you're looking for probs w/ a single loop you can find them at the VPlanet link [here](https://usaco.guide/general/expected?lang=cpp#getting-started).

**Pull request merged**
